.github/workflows/ci-pr.yml, .github/workflows/ci.yml, build.gradle, gradle/publish-artifactory.gradle, settings.gradle
* Will build and publish snapshot to Artifactory on push to main
=> Add initial CI workflow

build.gradle, spring-pulsar-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarAnnotationDrivenConfiguration.java, spring-pulsar-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarAutoConfiguration.java, spring-pulsar-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarProperties.java, spring-pulsar-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/PulsarAutoConfigurationTests.java, spring-pulsar/src/main/java/org/springframework/pulsar/config/PulsarListenerBeanNames.java, spring-pulsar/src/main/java/org/springframework/pulsar/core/CachingPulsarProducerFactory.java, spring-pulsar/src/main/java/org/springframework/pulsar/core/DefaultPulsarProducerFactory.java, spring-pulsar/src/main/java/org/springframework/pulsar/core/ProducerUtils.java, spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarProducerFactory.java, spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarTemplate.java, spring-pulsar/src/test/java/org/springframework/pulsar/core/CachingPulsarProducerFactoryTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/core/DefaultPulsarProducerFactoryTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/core/PulsarProducerFactoryTests.java, src/checkstyle/checkstyle.xml
=> Add caching producer factory

spring-pulsar/src/main/java/org/springframework/pulsar/core/CachingPulsarProducerFactory.java, spring-pulsar/src/test/java/org/springframework/pulsar/core/CachingPulsarProducerFactoryTests.java
This proposal enhances the producer cache key as follows:
1. Renamed to `ProducerCacheKey`
2. Uses `SchemaHash` to take into account schema bytes and schema type
ℹ️ NOTE: @alpreu @sobychacko we recently talked about doing something more sophisticated for the `MessageRouter` as part of the cache key. I ended up dropping that because those impls we were looking at (single, roundrobin) are really internal routers and not meant to be set by calling `ProducerBuilder.messageRouter`. Rather, these routers are custom (aka user-provided). If the custom router does not implement its own `EQ/HC` then it will fallback to identity `EQ/HC`. In a Spring based world it is highly likely that the router is a bean and there is only a single instance and this would cache well. If the user is passing in …
=> Use schema hash in producer cache key

spring-pulsar-docs/src/main/asciidoc/pulsar.adoc, spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarOperations.java, spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarTemplate.java, spring-pulsar/src/main/java/org/springframework/pulsar/core/TypedMessageBuilderCustomizer.java, spring-pulsar/src/test/java/org/springframework/pulsar/core/PulsarTemplateTests.java
This PR should implement keyed messaging on the PulsarTemplate (#26). 
A detailed description follows.
=> Implement keyed messages

tools/pulsar/docker/README.adoc, tools/pulsar/docker/standalone/pulsar-destroy.sh, tools/pulsar/docker/standalone/pulsar-start.sh, tools/pulsar/docker/standalone/pulsar-stop.sh
=> Add scripts to run standalone in Docker

spring-pulsar-dependencies/build.gradle, spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/AbstractContainerBaseTests.java
- Also updates docker image in autoconfigure base test
=> Update Pulsar client to 2.10.1

spring-pulsar-docs/src/main/asciidoc/index.adoc, spring-pulsar-docs/src/main/asciidoc/pulsar.adoc
* Also add Alex D. to author list
=> [DOCS] Move config props to collapsible panels

CONTRIBUTING.adoc, README.adoc, idea/codeStyleConfig.xml, spring-pulsar-docs/build.gradle
* Links to wiki from CONTRIBUTING.adoc
* Adds idea code style (it is mentioned in wiki)
* Adds asciidocs target in build (it is mentioned in wiki)
=> [DOCS] Support for new Wiki

.sdkmanrc
`.sdkmanrc` is used by sdkman to automatically switch to the version
declared in the file.
=> Add .sdkmanrc with 17.0.4-tem

spring-pulsar/src/main/java/org/springframework/pulsar/annotation/PulsarListenerAnnotationBeanPostProcessor.java, spring-pulsar/src/main/java/org/springframework/pulsar/config/AbstractPulsarListenerEndpoint.java, spring-pulsar/src/main/java/org/springframework/pulsar/config/ConcurrentPulsarListenerContainerFactory.java, spring-pulsar/src/main/java/org/springframework/pulsar/config/PulsarListenerEndpoint.java, spring-pulsar/src/main/java/org/springframework/pulsar/config/PulsarListenerEndpointAdapter.java, spring-pulsar/src/main/java/org/springframework/pulsar/listener/DefaultPulsarMessageListenerContainer.java, spring-pulsar/src/main/java/org/springframework/pulsar/listener/PulsarContainerProperties.java, spring-pulsar/src/test/java/org/springframework/pulsar/listener/DefaultPulsarMessageListenerContainerTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/listener/PulsarListenerTests.java
This PR implements the ability to use the 'topicPattern' param on PulsarListener (#5).
=> Implement topic pattern on PulsarListener (#5)

spring-pulsar/src/test/java/org/springframework/pulsar/listener/PulsarListenerTests.java
This PR fixes the test failures introduced here: https://github.com/spring-projects-experimental/spring-pulsar/pull/88#issuecomment-1238460618
=> Fix dead letter tests sharing the same topic

settings.gradle, spring-pulsar-sample-apps/build.gradle
=> Update SB plugin to 3.0.0-SNAPSHOT in sample apps

spring-pulsar-sample-apps/README.adoc, spring-pulsar-sample-apps/build.gradle
- `Tasks`
- `application`
- `bootRunApp1`
- `bootRunApp2`
=> Add custom tasks to run samples

spring-pulsar-docs/src/main/asciidoc/pulsar.adoc
- Native error handling in Pulsar
- PulsarConsumerErrorHnadler in Spring Pulsar
=> Error Handling Docs

gradle.properties
=> [Release 0.1.0-M1] Update version

spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/AuthParameterUtils.java, spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/WellKnownAuthParameters.java
This PR refactors the map in `WellKnownAuthParameters` to use constants for the individual parameters (#111)
=> Refactor: Define constants in WellKnownAuthParameters

spring-pulsar/src/main/java/org/springframework/pulsar/listener/DefaultPulsarMessageListenerContainer.java, spring-pulsar/src/test/java/org/springframework/pulsar/core/ConsumerAcknowledgmentTests.java
Resolves https://github.com/spring-projects-experimental/spring-pulsar/issues/120
=> Consolidate ACK/NACK calls in container

buildSrc/src/main/java/org/springframework/boot/gradle/JavaConventionsPlugin.java, spring-pulsar-sample-apps/build.gradle
=> Remove DNSResolverUtil error when running tests

spring-pulsar-docs/src/main/asciidoc/pulsar.adoc, spring-pulsar/src/main/java/org/springframework/pulsar/support/PulsarHeaders.java, spring-pulsar/src/test/java/org/springframework/pulsar/observation/ObservationIntegrationTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/observation/ObservationTests.java
Resovles https://github.com/spring-projects-experimental/spring-pulsar/issues/153
Disable observation tests temporarily
=> Pulsar header docs

spring-pulsar-docs/src/main/asciidoc/pulsar.adoc, spring-pulsar-sample-apps/build.gradle, spring-pulsar-sample-apps/src/main/resources/application.yml
Also documents how to configure Micrometer Observations.
See #147
=> Add Micrometer Tracing to sample apps

spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/PulsarPropertiesTests.java
For https://github.com/spring-projects-experimental/spring-pulsar/issues/176
=> Add test for producer properties

spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/PulsarReactivePropertiesTests.java
For https://github.com/spring-projects-experimental/spring-pulsar/issues/176
=> Add test for reactive sender properties

spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarReactiveProperties.java, spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/PulsarReactivePropertiesTests.java
=> Add test for reactive reader properties

spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarProperties.java, spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/PulsarPropertiesTests.java
=> Add test for client properties

buildSrc/build.gradle, spring-pulsar-dependencies/build.gradle, spring-pulsar-docs/build.gradle, spring-pulsar-sample-apps/sample-app1/build.gradle, spring-pulsar-sample-apps/sample-app2/build.gradle, spring-pulsar-sample-apps/sample-reactive/build.gradle
- Also update Micrometer docs gen to M7
=> Update to Spring Boot 3.0.0

spring-pulsar-spring-boot-autoconfigure/build.gradle, spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/SpringPulsarBootAppSanityTests.java, spring-pulsar/src/main/java/org/springframework/pulsar/core/CachingPulsarProducerFactory.java
- Required when template accessed via web request
=> Set proxy target class on caching producer factory

spring-pulsar/src/main/java/org/springframework/pulsar/annotation/PulsarListenerAnnotationBeanPostProcessor.java
- Removing unused code in PulsarListenerAnnotationBeanPostProcessor
=> Further removal of unused code

spring-pulsar-docs/src/main/asciidoc/intro.adoc, spring-pulsar-docs/src/main/asciidoc/pulsar.adoc, spring-pulsar-docs/src/main/asciidoc/reactive-pulsar.adoc
=> Update reactive docs

.github/workflows/ci-pr.yml, .github/workflows/ci.yml, .github/workflows/prepare-release.yml
Other prep for 0.1.0 release:
- special case 0.1.0 to avoid creating release branch
- minor format and name improvements in ci.yml
=> [Build] Enable sonatype publish

gradle.properties
=> [Release 0.1.0] Update version

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.adoc, README.adoc, spring-pulsar-docs/src/main/asciidoc/getting-help.adoc, spring-pulsar-docs/src/main/asciidoc/index.adoc
* Issue template
* Pull request template
* Add stackoverflow links
* Add getting help section
=> [Docs] Doc additions / guidelines

spring-pulsar/src/main/java/org/springframework/pulsar/support/converter/PulsarBatchMessageConverter.java, spring-pulsar/src/main/java/org/springframework/pulsar/support/converter/PulsarBatchMessagingMessageConverter.java, spring-pulsar/src/main/java/org/springframework/pulsar/support/converter/PulsarMessagingMessageConverter.java, spring-pulsar/src/main/java/org/springframework/pulsar/support/converter/PulsarRecordMessageConverter.java
- record/batch message converter cleanup
Resolves https://github.com/spring-projects-experimental/spring-pulsar/issues/264
=> Remove unused code

buildSrc/src/main/java/org/springframework/pulsar/gradle/docs/configprops/DocumentConfigurationProperties.java, spring-pulsar-docs/src/main/asciidoc/application-properties.adoc, spring-pulsar-docs/src/main/asciidoc/attributes.adoc, spring-pulsar-docs/src/main/asciidoc/copyright.adoc, spring-pulsar-docs/src/main/asciidoc/index.adoc, spring-pulsar-docs/src/main/asciidoc/pulsar-admin.adoc, spring-pulsar-docs/src/main/asciidoc/pulsar-function.adoc, spring-pulsar-spring-boot-autoconfigure/build.gradle, spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarAutoConfiguration.java, spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarProperties.java, spring-pulsar-spring-boot-autoconfigure/src/main/resources/META-INF/additional-spring-configuration-metadata.json, spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/PulsarAutoConfigurationTests.java, spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/PulsarFunctionTests.java, spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/PulsarPropertiesTests.java, spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/PulsarTestContainerSupport.java, spring-pulsar/build.gradle, spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarAdministration.java, spring-pulsar/src/main/java/org/springframework/pulsar/function/PulsarFunction.java, spring-pulsar/src/main/java/org/springframework/pulsar/function/PulsarFunctionAdministration.java, spring-pulsar/src/main/java/org/springframework/pulsar/function/PulsarFunctionOperations.java, spring-pulsar/src/main/java/org/springframework/pulsar/function/PulsarSink.java, spring-pulsar/src/main/java/org/springframework/pulsar/function/PulsarSource.java, spring-pulsar/src/main/java/org/springframework/pulsar/function/package-info.java, spring-pulsar/src/test/java/org/springframework/pulsar/function/PulsarFunctionAdministrationTests.java, spring-pulsar/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
=> Initial support for Pulsar IO and Connectors

spring-pulsar-docs/src/main/asciidoc/pulsar.adoc, spring-pulsar-docs/src/main/asciidoc/reactive-pulsar.adoc, spring-pulsar-docs/src/main/asciidoc/schema-info/PulsarListener/listener-snippet.adoc, spring-pulsar-docs/src/main/asciidoc/schema-info/ReactivePulsarListener/listener-snippet.adoc, spring-pulsar-docs/src/main/asciidoc/schema-info/schema-info-listener.adoc, spring-pulsar-docs/src/main/asciidoc/schema-info/schema-info-template.adoc, spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/PulsarAutoConfigurationTests.java, spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/PulsarListenerTests.java, spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/PulsarReactiveAutoConfigurationTests.java, spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/ReactivePulsarListenerTests.java
=> Adds docs and ITs for custom schema mappings

spring-pulsar-sample-apps/sample-pulsar-binder/src/main/resources/application.yml, spring-pulsar-spring-cloud-stream-binder/src/main/java/org/springframework/pulsar/spring/cloud/stream/binder/PulsarMessageChannelBinder.java, spring-pulsar-spring-cloud-stream-binder/src/main/java/org/springframework/pulsar/spring/cloud/stream/binder/config/PulsarBinderConfiguration.java, spring-pulsar-spring-cloud-stream-binder/src/main/java/org/springframework/pulsar/spring/cloud/stream/binder/properties/PulsarProducerProperties.java, spring-pulsar-spring-cloud-stream-binder/src/test/java/org/springframework/pulsar/spring/cloud/stream/binder/PulsarBinderIntegrationTests.java
=> Pulsar binder schema related changes

spring-pulsar-sample-apps/sample-pulsar-binder/src/main/java/org/springframework/pulsar/sample/binder/SpringPulsarBinderSampleApp.java, spring-pulsar-sample-apps/sample-pulsar-binder/src/main/resources/application.yml
Use 2 different types of schema now that the setSchema is thread-safe.
=> Update SCSt binder sample

spring-pulsar/src/main/java/org/springframework/pulsar/core/DefaultPulsarReaderFactory.java, spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarReaderFactory.java, spring-pulsar/src/test/java/org/springframework/pulsar/core/DefaultPulsarReaderFactoryTests.java
=> Basic Pulsar Reader API support in Spring Pulsar

spring-pulsar/src/main/java/org/springframework/pulsar/core/DefaultPulsarConsumerFactory.java, spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarConsumerFactory.java, spring-pulsar/src/main/java/org/springframework/pulsar/listener/DefaultPulsarMessageListenerContainer.java, spring-pulsar/src/test/java/org/springframework/pulsar/core/ConsumerTestUtils.java, spring-pulsar/src/test/java/org/springframework/pulsar/core/DefaultPulsarConsumerFactoryTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/listener/ConcurrentPulsarMessageListenerContainerTests.java
- Simplify API to single method
- Add subscriptionName
- Add test for DefaultPulsarConsumerFactory
ℹ️ **NOTE:** ~I will update docs in another PR or subsequent commit to this PR (just getting the base out there for review)~No doc updates needed
=> Improve ConsumerFactory API

buildSrc/build.gradle, spring-pulsar-dependencies/build.gradle, spring-pulsar-sample-apps/sample-app1/build.gradle, spring-pulsar-sample-apps/sample-app2/build.gradle, spring-pulsar-sample-apps/sample-app2/src/main/java/app2/FailoverConsumerApp.java, spring-pulsar-sample-apps/sample-pulsar-binder/build.gradle, spring-pulsar-sample-apps/sample-pulsar-functions/sample-signup-app/build.gradle, spring-pulsar-sample-apps/sample-reactive/build.gradle
Also update:
* testcontainersVersion = '1.17.6'
* springCloudStreamVersion = '4.0.1'
=> Update Spring Boot 3.0.2

buildSrc/src/main/java/org/springframework/boot/gradle/classpath/CheckClasspathForProhibitedDependencies.java, buildSrc/src/main/java/org/springframework/pulsar/gradle/versions/UpdateToSnapshotVersionTask.java, spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/config/annotation/ReactivePulsarListenerAnnotationBeanPostProcessor.java, spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/core/DefaultReactivePulsarSenderFactory.java, spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/core/ReactivePulsarTemplate.java, spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/core/DefaultReactiveMessageConsumerFactoryTests.java, spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/core/DefaultReactiveMessageReaderFactoryTests.java, spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/core/ReactivePulsarTemplateTests.java, spring-pulsar/src/main/java/org/springframework/pulsar/annotation/PulsarListenerAnnotationBeanPostProcessor.java, spring-pulsar/src/main/java/org/springframework/pulsar/config/PulsarClientFactoryBean.java, spring-pulsar/src/main/java/org/springframework/pulsar/core/CachingPulsarProducerFactory.java, spring-pulsar/src/main/java/org/springframework/pulsar/core/DefaultPulsarProducerFactory.java, spring-pulsar/src/main/java/org/springframework/pulsar/core/ProducerUtils.java, spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarAdministration.java, spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarTemplate.java, spring-pulsar/src/main/java/org/springframework/pulsar/function/PulsarFunctionAdministration.java, spring-pulsar/src/main/java/org/springframework/pulsar/listener/DefaultPulsarMessageListenerContainer.java, spring-pulsar/src/main/java/org/springframework/pulsar/listener/PulsarDeadLetterPublishingRecoverer.java
=> Misc cleanups

spring-pulsar/src/main/java/org/springframework/pulsar/core/CachingPulsarProducerFactory.java, spring-pulsar/src/main/java/org/springframework/pulsar/core/DefaultPulsarProducerFactory.java, spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarProducerFactory.java, spring-pulsar/src/test/java/org/springframework/pulsar/core/DefaultPulsarProducerFactoryTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/core/PulsarProducerFactoryTests.java
The `createProducer(Schema)` is not useful in that most users will specify a topic and not rely on the default to send to
=> Trim PulsarProducerFactory API

spring-pulsar/src/test/java/org/springframework/pulsar/core/SharedSubscriptionConsumerTests.java
=> Trying to fix failing test in shared subscription

spring-pulsar-dependencies/build.gradle, spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/core/ReactivePulsarOperations.java, spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/core/ReactivePulsarTemplate.java, spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/core/ReactivePulsarTemplateTests.java, spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/listener/DefaultReactivePulsarMessageListenerContainerTests.java, spring-pulsar-sample-apps/sample-reactive/src/main/java/org.springframework.pulsar.example/ReactiveSpringPulsarBootApp.java
=> Bump the Pulsar reactive client to 0.2.0

spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarAutoConfiguration.java, spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarProperties.java, spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/PulsarAutoConfigurationTests.java, spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/PulsarPropertiesTests.java
Resolves https://github.com/spring-projects-experimental/spring-pulsar/issues/328
=> Pulsar Reader auto config (imperative)

spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/core/ReactivePulsarTemplateTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/core/PulsarTemplateTests.java
=> Harmonize tests between PulsarTemplate and ReactivePulsarTemplate

spring-pulsar-docs/src/main/asciidoc/application-properties.adoc
=> Add reader application properties doc

spring-pulsar-docs/src/main/asciidoc/authentication.adoc, spring-pulsar-docs/src/main/asciidoc/index.adoc, spring-pulsar-docs/src/main/asciidoc/pulsar-function.adoc, spring-pulsar-docs/src/main/asciidoc/pulsar.adoc, spring-pulsar-docs/src/main/asciidoc/reactive-pulsar.adoc
- Use template var for pulsar docs url
=> Add PulsarReader section to docs

.github/workflows/ci-pr.yml, spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/PulsarFunctionAdministrationIntegrationTests.java
* Enable the IT run on CI-PR workflow
* Add Junit5 TestWatcher to log the Pulsar container logs on test failure
=> Attempt to fix PulsarFunctionAdministration IT

spring-pulsar/src/main/java/org/springframework/pulsar/reader/DefaultPulsarReaderListenerContainer.java
=> Implement stop() in reader container

spring-pulsar-docs/build.gradle, spring-pulsar-docs/src/main/asciidoc/attributes.adoc
=> Make spring-cloud-stream version dynamic in docs

spring-pulsar-docs/src/main/asciidoc/pulsar-binder.adoc, spring-pulsar-docs/src/main/asciidoc/pulsar-header.adoc
=> Add header mapper docs to binder docs

.github/workflows/ci-pr.yml, spring-pulsar-docs/src/main/asciidoc/pulsar-header.adoc
- Also include jacoco upload to ci-pr.yml
=> Remove heading from pulsar-header.adoc

README.adoc, buildSrc/build.gradle, spring-pulsar-dependencies/build.gradle, spring-pulsar-sample-apps/sample-app1/build.gradle, spring-pulsar-sample-apps/sample-app2/build.gradle, spring-pulsar-sample-apps/sample-pulsar-binder/build.gradle, spring-pulsar-sample-apps/sample-pulsar-functions/sample-signup-app/build.gradle, spring-pulsar-sample-apps/sample-pulsar-reader/build.gradle, spring-pulsar-sample-apps/sample-reactive/build.gradle
=> Update to Spring Boot 3.0.4

buildSrc/build.gradle, spring-pulsar-dependencies/build.gradle, spring-pulsar-sample-apps/sample-app1/build.gradle, spring-pulsar-sample-apps/sample-app2/build.gradle, spring-pulsar-sample-apps/sample-pulsar-binder/build.gradle, spring-pulsar-sample-apps/sample-pulsar-functions/sample-signup-app/build.gradle, spring-pulsar-sample-apps/sample-pulsar-reader/build.gradle, spring-pulsar-sample-apps/sample-reactive/build.gradle
=> Update Spring Boot 3.0.5

spring-pulsar/src/main/java/org/springframework/pulsar/aot/PulsarRuntimeHints.java
=> Add LinkedHashMap to AOT hints

gradle.properties
=> [Release 0.2.0] Update version

README.adoc, spring-pulsar/src/main/java/org/springframework/pulsar/aot/PulsarRuntimeHints.java
* Add new module descriptions to README.adoc
* Replace non-shaded Caffeine classes w/ shaded version in PulsarRuntimeHints.java
=> Follow up on shaded cache modules

gradle.properties
=> Update core version to 1.0.0-SNAPSHOT

spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/ConsumerConfigProperties.java, spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarAutoConfiguration.java, spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarProperties.java, spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/PulsarAutoConfigurationTests.java, spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/PulsarPropertiesTests.java, spring-pulsar-spring-cloud-stream-binder/src/main/java/org/springframework/pulsar/spring/cloud/stream/binder/PulsarBinderUtils.java, spring-pulsar-spring-cloud-stream-binder/src/main/java/org/springframework/pulsar/spring/cloud/stream/binder/PulsarMessageChannelBinder.java, spring-pulsar-spring-cloud-stream-binder/src/test/java/org/springframework/pulsar/spring/cloud/stream/binder/PulsarBinderConfigurationPropertiesTests.java, spring-pulsar-spring-cloud-stream-binder/src/test/java/org/springframework/pulsar/spring/cloud/stream/binder/PulsarBinderIntegrationTests.java, spring-pulsar-spring-cloud-stream-binder/src/test/java/org/springframework/pulsar/spring/cloud/stream/binder/PulsarBinderTests.java, spring-pulsar-spring-cloud-stream-binder/src/test/java/org/springframework/pulsar/spring/cloud/stream/binder/PulsarBinderUtilsTests.java, spring-pulsar-spring-cloud-stream-binder/src/test/java/org/springframework/pulsar/spring/cloud/stream/binder/PulsarExtendedBindingPropertiesTests.java, spring-pulsar/src/main/java/org/springframework/pulsar/core/DefaultPulsarConsumerFactory.java, spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarConsumerFactory.java, spring-pulsar/src/test/java/org/springframework/pulsar/core/ConsumerAcknowledgmentTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/core/DefaultPulsarConsumerFactoryTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/core/FailoverConsumerTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/core/SharedSubscriptionConsumerTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/listener/DefaultPulsarConsumerErrorHandlerTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/listener/DefaultPulsarMessageListenerContainerTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/listener/PulsarListenerTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/observation/ObservationIntegrationTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/observation/ObservationTests.java
- Move consumer props 'toMap' into PulsarBinderUtils
=> Use builder to autoconfigure PulsarConsumerFactory

spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarAutoConfiguration.java, spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarProperties.java, spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/PulsarAutoConfigurationTests.java, spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/PulsarPropertiesTests.java, spring-pulsar/src/main/java/org/springframework/pulsar/core/DefaultPulsarReaderFactory.java, spring-pulsar/src/test/java/org/springframework/pulsar/core/DefaultPulsarReaderFactoryTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/reader/DefaultPulsarMessageReaderContainerTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/reader/PulsarReaderTests.java
=> Use builder to autoconfigure PulsarReaderFactory

spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/listener/ReactivePulsarListenerTests.java, spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarAutoConfiguration.java, spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarProperties.java, spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/PulsarPropertiesTests.java, spring-pulsar-spring-cloud-stream-binder/src/test/java/org/springframework/pulsar/spring/cloud/stream/binder/PulsarBinderTests.java, spring-pulsar/src/main/java/org/springframework/pulsar/core/DefaultPulsarClientFactory.java, spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarAdminBuilderCustomizer.java, spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarAdministration.java, spring-pulsar/src/test/java/org/springframework/pulsar/core/PulsarAdministrationTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/listener/PulsarListenerTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/observation/ObservationIntegrationTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/observation/ObservationTests.java
=> Use builder to autoconfigure PulsarAdministration

spring-pulsar-dependencies/build.gradle, spring-pulsar-docs/src/main/asciidoc/attributes-variables.adoc, spring-pulsar-sample-apps/sample-pulsar-functions/download-connectors.sh, spring-pulsar-sample-apps/sample-pulsar-functions/sample-signup-function/build.gradle, spring-pulsar-test/src/main/java/org/springframework/pulsar/test/support/PulsarTestContainerSupport.java, tools/pulsar/docker/standalone/pulsar-start.sh
=> Update Pulsar 3.0.0

spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/PulsarPropertiesTests.java
Adds test coverage for:
- ProducerConfigProperties.toProducerBuilderCustomizer()
- ConsumerConfigProperties.toConsumerBuilderCustomizer()
Switch to BDDMockito style verification because:
1. `PulsarProperties` (and this test) is being kept in sync with the Spring Boot PR until it is merged
2. Spring Boot requires BDDMockito style verification
=> Add tests for PulsarProperties toCustomizer API

spring-pulsar-docs/spring-pulsar-docs.gradle, spring-pulsar-docs/src/main/asciidoc/attributes-variables.adoc, spring-pulsar-docs/src/main/asciidoc/index.adoc, spring-pulsar-docs/src/main/asciidoc/intro.adoc, spring-pulsar-docs/src/main/asciidoc/version-compatibility.adoc
=> [Docs] Add version compatibility appendix

spring-pulsar-docs/src/main/asciidoc/index.adoc, spring-pulsar-docs/src/main/asciidoc/override-boot-dependencies.adoc
=> [Docs] Add boot version override appendix

spring-pulsar-docs/spring-pulsar-docs.gradle, spring-pulsar-docs/src/main/asciidoc/attributes-variables.adoc, spring-pulsar-docs/src/main/asciidoc/index.adoc
- If the project version is a SNAPSHOT a warning is added at the top of the docs stating this fact.
- Also adds a "Project Status" section to describe the versions, evolution of the project, which version to use, etc..
=> [Docs] Add warning for snapshot docs

README.adoc, spring-pulsar-docs/src/main/asciidoc/intro.adoc, spring-pulsar-docs/src/main/asciidoc/project-state.adoc, spring-pulsar-docs/src/main/asciidoc/version-compatibility.adoc
=> [Docs] Add project status/evolution section

buildSrc/build.gradle, gradle.properties, spring-pulsar-sample-apps/sample-app1/build.gradle, spring-pulsar-sample-apps/sample-app2/build.gradle, spring-pulsar-sample-apps/sample-pulsar-binder/build.gradle, spring-pulsar-sample-apps/sample-pulsar-functions/sample-signup-app/build.gradle, spring-pulsar-sample-apps/sample-pulsar-reader/build.gradle
=> Update to Spring Boot 3.2.0-SNAPSHOT

buildSrc/build.gradle, gradle.properties, spring-pulsar-dependencies/spring-pulsar-dependencies.gradle, spring-pulsar/spring-pulsar.gradle
=> Narrow refs to Spring Boot

gradle.properties
=> [Release 1.0.0-M1] Update version

gradle.properties, spring-pulsar-sample-apps/sample-pulsar-functions/sample-signup-function/build.gradle, spring-pulsar-test/src/main/java/org/springframework/pulsar/test/support/PulsarTestContainerSupport.java
=> Update to Pulsar client 3.0.1

spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/aot/ReactivePulsarRuntimeHints.java, spring-pulsar/src/main/java/org/springframework/pulsar/aot/PulsarRuntimeHints.java
This allows running on GraalVM 23.1.0-dev.
=> Add PulsarClientImplementationBindingImpl to AOT reflection hints.

spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarAdministration.java, spring-pulsar/src/test/java/org/springframework/pulsar/core/PulsarAdministrationIntegrationTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/core/PulsarAdministrationTests.java
=> PulsarAdministration accepts multiple customizers

spring-pulsar/src/main/java/org/springframework/pulsar/core/CachingPulsarProducerFactory.java, spring-pulsar/src/main/java/org/springframework/pulsar/core/DefaultPulsarProducerFactory.java, spring-pulsar/src/test/java/org/springframework/pulsar/core/CachingPulsarProducerFactoryTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/core/DefaultPulsarProducerFactoryTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/core/FailoverConsumerTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/core/PulsarProducerFactoryTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/core/SharedSubscriptionConsumerTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/listener/PulsarListenerTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/reader/DefaultPulsarMessageReaderContainerTests.java
=> DefaultPulsarProducerFactory accepts multiple customizers

spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/core/DefaultReactivePulsarSenderFactory.java, spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/core/DefaultReactivePulsarConsumerFactoryTests.java, spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/core/DefaultReactivePulsarReaderFactoryTests.java, spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/core/DefaultReactivePulsarSenderFactoryTests.java, spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/core/ReactivePulsarTemplateTests.java, spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/listener/DefaultReactivePulsarMessageListenerContainerTests.java, spring-pulsar/src/main/java/org/springframework/pulsar/core/DefaultPulsarConsumerFactory.java, spring-pulsar/src/main/java/org/springframework/pulsar/core/DefaultPulsarProducerFactory.java, spring-pulsar/src/main/java/org/springframework/pulsar/core/DefaultPulsarReaderFactory.java, spring-pulsar/src/test/java/org/springframework/pulsar/core/ConsumerAcknowledgmentTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/core/DefaultPulsarConsumerFactoryTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/core/DefaultPulsarReaderFactoryTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/core/FailoverConsumerTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/core/SharedSubscriptionConsumerTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/listener/DefaultPulsarConsumerErrorHandlerTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/listener/DefaultPulsarMessageListenerContainerTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/reader/DefaultPulsarMessageReaderContainerTests.java
- DefaultPulsarConsumerFactory
- DefaultPulsarReaderFactory
- DefaultReactivePulsarSenderFactory
See #432
=> Allow multiple customizers for several components

gradle.properties, spring-pulsar-docs/src/main/asciidoc/override-boot-dependencies.adoc, spring-pulsar-sample-apps/sample-pulsar-functions/download-connectors.sh, spring-pulsar-sample-apps/sample-pulsar-functions/sample-signup-function/build.gradle, spring-pulsar-test/src/main/java/org/springframework/pulsar/test/support/PulsarTestContainerSupport.java, tools/pulsar/docker/standalone/pulsar-start.sh
=> Update to Pulsar v3.1.0

gradle.properties, integration-tests/integration-tests.gradle, integration-tests/src/intTest/java/org/springframework/pulsar/autoconfigure/PulsarFunctionAdministrationIntegrationTests.java, spring-pulsar-dependencies/spring-pulsar-dependencies.gradle, spring-pulsar-docs/spring-pulsar-docs.gradle, spring-pulsar-docs/src/main/asciidoc/attributes-variables.adoc, spring-pulsar-docs/src/main/asciidoc/pulsar-admin.adoc, spring-pulsar-docs/src/main/asciidoc/pulsar-binder.adoc, spring-pulsar-docs/src/main/asciidoc/quick-tour.adoc, spring-pulsar-docs/src/main/asciidoc/reactive-quick-tour.adoc, spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/listener/ReactivePulsarListenerTests.java, spring-pulsar-sample-apps/sample-app1/build.gradle, spring-pulsar-sample-apps/sample-app2/build.gradle, spring-pulsar-sample-apps/sample-pulsar-binder/build.gradle, spring-pulsar-sample-apps/sample-pulsar-functions/sample-signup-app/build.gradle, spring-pulsar-sample-apps/sample-pulsar-functions/sample-signup-function/build.gradle, spring-pulsar-sample-apps/sample-pulsar-reader/build.gradle, spring-pulsar-sample-apps/sample-reactive/build.gradle
=> Use Spring Boot Pulsar starters

CONTRIBUTING.adoc, README.adoc, spring-pulsar-docs/spring-pulsar-docs.gradle, spring-pulsar-docs/src/main/asciidoc/intro.adoc, spring-pulsar-docs/src/main/asciidoc/observability.adoc, spring-pulsar-docs/src/main/asciidoc/override-boot-dependencies.adoc, spring-pulsar-docs/src/main/asciidoc/pulsar.adoc, spring-pulsar-docs/src/main/asciidoc/schema-info/schema-info-listener.adoc, spring-pulsar-docs/src/main/asciidoc/schema-info/schema-info-template.adoc
`"spring pulsar" -> "Spring for Apache Pulsar"`
cc: @markt-asf
=> Adjust project naming in docs

spring-pulsar-docs/src/main/asciidoc/attributes-variables.adoc, spring-pulsar-docs/src/main/asciidoc/authentication.adoc, spring-pulsar-docs/src/main/asciidoc/pulsar.adoc, spring-pulsar-docs/src/main/asciidoc/tls-encryption.adoc
=> Add SSL docs and update authentication samples accordingly.

gradle.properties
=> [Release 1.0.0-M2] Update version

spring-pulsar-docs/src/main/asciidoc/quick-tour.adoc, spring-pulsar-docs/src/main/asciidoc/reactive-quick-tour.adoc
=> Clarify dependency coordinates for 0.2.x

spring-pulsar-docs/src/main/asciidoc/project-state.adoc, spring-pulsar-docs/src/main/asciidoc/version-compatibility.adoc
=> Clarify dependency coordinates in documentation

spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/listener/DefaultReactivePulsarMessageListenerContainer.java, spring-pulsar/src/main/java/org/springframework/pulsar/config/GenericListenerEndpointRegistry.java, spring-pulsar/src/main/java/org/springframework/pulsar/config/GenericReaderEndpointRegistry.java, spring-pulsar/src/main/java/org/springframework/pulsar/config/PulsarListenerEndpointRegistrar.java, spring-pulsar/src/main/java/org/springframework/pulsar/config/PulsarReaderEndpointRegistrar.java, spring-pulsar/src/main/java/org/springframework/pulsar/listener/AbstractPulsarMessageListenerContainer.java, spring-pulsar/src/main/java/org/springframework/pulsar/listener/DefaultPulsarMessageListenerContainer.java, spring-pulsar/src/main/java/org/springframework/pulsar/reader/AbstractPulsarMessageReaderContainer.java
See #414
Use ReentrantLocks to avoid unnecessary virtual thread pinning.
=> GH-414: Avoid I/O in synchronized blocks

.github/workflows/deploy-docs.yml, antora-playbook.yml
Include future branches and tags, but exclude old tags and branches that do not contain Antora builds
=> Fix deploy-docs.yml content sources

spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/core/DefaultReactivePulsarSenderFactory.java, spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarClientProxy.java
=> Make PulsarClientProxy package protected

buildSrc/src/main/java/org/springframework/pulsar/gradle/SpringDocsModulePlugin.java, buildSrc/src/main/java/org/springframework/pulsar/gradle/publish/MavenPublishingConventionsPlugin.java, buildSrc/src/main/java/org/springframework/pulsar/gradle/publish/PublishAllJavaComponentsPlugin.java, spring-pulsar-docs/spring-pulsar-docs.gradle
=> Do not sign directories in artifacts (Gradle 8 workaround)

gradle.properties
=> Update Reactive Pulsar Client 0.4.0

gradle/antora-docs.gradle, spring-pulsar-docs/src/main/antora/antora-playbook.yml
References new messaging category in this PR https://github.com/spring-io/antora-ui-spring/pull/175
=> Update to new antora docs ui

gradle.properties, spring-pulsar-dependencies/spring-pulsar-dependencies.gradle
=> Update several library patch versions

gradle/aggregate-jacoco-report.gradle, spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/core/DefaultReactivePulsarSenderFactory.java
=> Fully clear reactive sender cache on Lifecycle stop

gradle.properties
=> [Release 1.0.0-RC1] Update version

README.adoc
=> Fix links to ref docs in README.adoc

spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/core/DefaultReactivePulsarSenderFactory.java
See https://github.com/spring-projects/spring-boot/issues/38161
=> Make reflective clear Reactive cache more robust

spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/pulsar.adoc, spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/reactive-pulsar.adoc
=> Clarify use of default subscription name in @PulsarListener

spring-pulsar/src/main/java/org/springframework/pulsar/listener/DefaultPulsarMessageListenerContainer.java
=> Safe close message listener container consumer

spring-pulsar-dependencies/spring-pulsar-dependencies.gradle
=> Update Reactor and Micrometer to GA

gradle.properties
=> Update to Spring Framework 6.1.0

gradle.properties
=> Update Pulsar reactive client to v0.5.0

gradle.properties, integration-tests/integration-tests.gradle, spring-pulsar-sample-apps/sample-pulsar-functions/download-connectors.sh, spring-pulsar-sample-apps/sample-pulsar-functions/sample-signup-function/build.gradle, spring-pulsar-test/src/main/java/org/springframework/pulsar/test/support/PulsarTestContainerSupport.java, tools/pulsar/docker/standalone/pulsar-start.sh
=> Update to Pulsar client 3.1.1

gradle.properties
=> [Release 1.0.0] Update version

integration-tests/integration-tests.gradle, integration-tests/src/intTest/java/org/springframework/pulsar/inttest/listener/ReactivePulsarListenerIntegrationTests.java
=> Fix ReactivePulsarListenerIntegrationTests use of customizer

spring-pulsar-sample-apps/sample-imperative-produce-consume/build.gradle, spring-pulsar-sample-apps/sample-imperative-produce-consume/compose.yaml, spring-pulsar-sample-apps/sample-imperative-produce-consume/src/main/resources/application.yml
=> Add docker-compose support to sample-imperative-produce-consume app

spring-pulsar-docs/src/main/antora/modules/ROOT/nav.adoc, spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/reactive-pulsar.adoc, spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/tombstones-reactive.adoc, spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/tombstones.adoc, spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/config/MethodReactivePulsarListenerEndpoint.java, spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/listener/ReactivePulsarListenerTests.java, spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/listener/ReactivePulsarListenerTestsBase.java, spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/listener/ReactivePulsarListenerTombstoneTests.java, spring-pulsar/src/main/java/org/springframework/pulsar/annotation/AbstractPulsarAnnotationsBeanPostProcessor.java, spring-pulsar/src/main/java/org/springframework/pulsar/annotation/PulsarNullAwarePayloadArgumentResolver.java, spring-pulsar/src/main/java/org/springframework/pulsar/annotation/PulsarReaderAnnotationBeanPostProcessor.java, spring-pulsar/src/main/java/org/springframework/pulsar/config/MethodPulsarListenerEndpoint.java, spring-pulsar/src/main/java/org/springframework/pulsar/config/MethodPulsarReaderEndpoint.java, spring-pulsar/src/main/java/org/springframework/pulsar/support/PulsarNull.java, spring-pulsar/src/main/java/org/springframework/pulsar/support/converter/PulsarMessageConverter.java, spring-pulsar/src/main/java/org/springframework/pulsar/support/converter/PulsarRecordMessageConverter.java, spring-pulsar/src/test/java/org/springframework/pulsar/function/PulsarFunctionAdministrationTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/listener/PulsarListenerTestsBase.java, spring-pulsar/src/test/java/org/springframework/pulsar/listener/PulsarListenerTombstoneTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/reader/PulsarReaderBasicTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/reader/PulsarReaderStartMessageIdTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/reader/PulsarReaderTestsBase.java, spring-pulsar/src/test/resources/logback-test.xml
=> Add tombstone support to listeners

gradle.properties, spring-pulsar-dependencies/spring-pulsar-dependencies.gradle, spring-pulsar-sample-apps/sample-pulsar-binder/build.gradle, spring-pulsar-sample-apps/sample-pulsar-functions/sample-signup-app/build.gradle, spring-pulsar-sample-apps/sample-pulsar-reader/build.gradle, spring-pulsar-sample-apps/sample-reactive/build.gradle
=> Update Spring Boot dependencies for 3.2.1-SNAPSHOT

gradle/wrapper/gradle-wrapper.properties, gradlew
=> Update Gradle 8.5

spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/core/DefaultReactivePulsarSenderFactory.java
Fixes https://github.com/spring-projects/spring-boot/issues/38161
=> Close cache safely in DefaultReactivePulsarSenderFactory close()

.github/workflows/ci.yml
=> Update spring-doc-actions to v0.0.13

gradle.properties
=> Update Spring Framework to 6.1.2

.github/workflows/ci.yml
Previously a new branch was created and tagged for every GA release. This commit removes the branch creation and simply tags the current branch with the release version.
Resolves #498
=> [CI] Do not create branch for new release

spring-pulsar-dependencies/spring-pulsar-dependencies.gradle
=> Update Spring Retry 2.0.5

gradle.properties
=> Update Pulsar Reactive Client to 0.5.1

gradle.properties
=> [Release 1.0.1] Update version

gradle.properties, spring-pulsar-sample-apps/sample-failover-custom-router/build.gradle, spring-pulsar-sample-apps/sample-imperative-produce-consume/build.gradle, spring-pulsar-sample-apps/sample-pulsar-binder/build.gradle, spring-pulsar-sample-apps/sample-pulsar-functions/sample-signup-app/build.gradle, spring-pulsar-sample-apps/sample-pulsar-reader/build.gradle, spring-pulsar-sample-apps/sample-reactive/build.gradle
=> Update to Spring Boot 3.2.2-SNAPSHOT

build.gradle, buildSrc/build.gradle, buildSrc/settings.gradle, buildSrc/src/main/java/org/springframework/pulsar/gradle/AbstractSpringModulePlugin.java, buildSrc/src/main/java/org/springframework/pulsar/gradle/JavaConventionsPlugin.java, buildSrc/src/main/java/org/springframework/pulsar/gradle/check/JacocoConventionsPlugin.java, buildSrc/src/main/java/org/springframework/pulsar/gradle/versions/UpdateProjectVersionTask.java, buildSrc/src/main/java/org/springframework/pulsar/gradle/versions/UpdateToReleaseVersionTask.java, buildSrc/src/main/java/org/springframework/pulsar/gradle/versions/UpdateToSnapshotVersionTask.java, gradle.properties, gradle/aggregate-jacoco-report.gradle, gradle/antora-docs.gradle, gradle/build-libs.versions.toml, gradle/libs.versions.toml, gradle/version-catalog-update.gradle, integration-tests/integration-tests.gradle, spring-pulsar-cache-provider-caffeine/spring-pulsar-cache-provider-caffeine.gradle, spring-pulsar-dependencies/spring-pulsar-dependencies.gradle, spring-pulsar-docs/spring-pulsar-docs.gradle, spring-pulsar-reactive/spring-pulsar-reactive.gradle, spring-pulsar-sample-apps/sample-failover-custom-router/build.gradle, spring-pulsar-sample-apps/sample-imperative-produce-consume/build.gradle, spring-pulsar-sample-apps/sample-pulsar-binder/build.gradle, spring-pulsar-sample-apps/sample-pulsar-functions/sample-signup-app/build.gradle, spring-pulsar-sample-apps/sample-pulsar-functions/sample-signup-function/build.gradle, spring-pulsar-sample-apps/sample-pulsar-reader/build.gradle, spring-pulsar-sample-apps/sample-reactive/build.gradle, spring-pulsar/spring-pulsar.gradle
=> Use version catalog to drive java platform

README.adoc, settings.gradle, spring-pulsar-bom/spring-pulsar-bom.gradle, spring-pulsar-docs/src/main/antora/modules/ROOT/nav.adoc, spring-pulsar-docs/src/main/antora/modules/ROOT/pages/appendix/getting-dependencies-without-boot.adoc, spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/listener/ReactivePulsarListenerTombstoneTests.java
=> Add BOM (spring-pulsar-bom) module

buildSrc/build.gradle, buildSrc/src/main/java/org/springframework/pulsar/gradle/MavenBomPlugin.groovy, spring-pulsar-bom/spring-pulsar-bom.gradle
=> Adjust BOM to include java platform

.github/workflows/check-samples.yml, spring-pulsar-sample-apps/sample-apps-check-ci.gradle, spring-pulsar-sample-apps/sample-failover-custom-router/build.gradle, spring-pulsar-sample-apps/sample-failover-custom-router/src/main/resources/application.yml, spring-pulsar-sample-apps/sample-imperative-produce-consume/build.gradle, spring-pulsar-sample-apps/sample-imperative-produce-consume/src/main/resources/application.yml
=> [CI] Add Spring Boot 3.3.0-SNAPSHOT compatibility check

spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/authentication.adoc
=> Add doc for workaround for env var auth params

gradle/libs.versions.toml, spring-pulsar-sample-apps/sample-failover-custom-router/build.gradle
=> Update to Brave 6.0.1

buildSrc/src/main/java/org/springframework/pulsar/gradle/versions/UpdateProjectVersionPlugin.java, buildSrc/src/main/java/org/springframework/pulsar/gradle/versions/UpdateProjectVersionTask.java, buildSrc/src/main/java/org/springframework/pulsar/gradle/versions/UpdateToNextBootSnapshotVersionTask.java, buildSrc/src/main/java/org/springframework/pulsar/gradle/versions/UpdateToSnapshotVersionTask.java
=> CI updates from 1.0.x

gradle/libs.versions.toml
=> Update to pulsar-client-reactive 0.5.3

gradle/libs.versions.toml
=> Update to Reactor 2023.0.4

spring-pulsar/src/main/java/org/springframework/pulsar/core/ProducerBuilderConfigurationUtil.java
This utility class is only used by the Pulsar SCSt binder and the functionality has been moved into the binder project.
=> Deprecate ProducerBuilderConfigurationUtil

gradle/libs.versions.toml
=> Update Spring Framework 6.1.5

spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/pulsar.adoc, spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarTemplate.java, spring-pulsar/src/test/java/org/springframework/pulsar/core/PulsarTemplateTests.java
=> Backport "Producer Cache becomes ineffective when ProducerBuilderCustomizer is configured"

spring-pulsar-test/src/main/java/org/springframework/pulsar/test/support/PulsarTestContainerSupport.java
=> Remove stop method from PulsarTestContainerSupport

spring-pulsar-test/src/main/java/org/springframework/pulsar/test/support/PulsarConsumerTestUtil.java, spring-pulsar-test/src/test/java/org/springframework/pulsar/test/support/PulsarConsumerTestUtilTests.java
=> Close created client in PulsarConsumerTestUtil

spring-pulsar/spring-pulsar.gradle, spring-pulsar/src/main/java/org/springframework/pulsar/PulsarException.java, spring-pulsar/src/main/java/org/springframework/pulsar/annotation/PulsarListener.java, spring-pulsar/src/main/java/org/springframework/pulsar/annotation/PulsarListenerAnnotationBeanPostProcessor.java, spring-pulsar/src/main/java/org/springframework/pulsar/config/ConcurrentPulsarListenerContainerFactory.java, spring-pulsar/src/main/java/org/springframework/pulsar/config/MethodPulsarListenerEndpoint.java, spring-pulsar/src/main/java/org/springframework/pulsar/core/DefaultPulsarProducerFactory.java, spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarProducerFactory.java, spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarTemplate.java, spring-pulsar/src/main/java/org/springframework/pulsar/listener/DefaultPulsarMessageListenerContainer.java, spring-pulsar/src/main/java/org/springframework/pulsar/listener/PulsarContainerProperties.java, spring-pulsar/src/main/java/org/springframework/pulsar/transaction/PulsarAwareTransactionManager.java, spring-pulsar/src/main/java/org/springframework/pulsar/transaction/PulsarResourceHolder.java, spring-pulsar/src/main/java/org/springframework/pulsar/transaction/PulsarResourceSynchronization.java, spring-pulsar/src/main/java/org/springframework/pulsar/transaction/PulsarTransactionManager.java, spring-pulsar/src/main/java/org/springframework/pulsar/transaction/PulsarTransactionObject.java, spring-pulsar/src/main/java/org/springframework/pulsar/transaction/PulsarTransactionUtils.java, spring-pulsar/src/main/java/org/springframework/pulsar/transaction/package-info.java, spring-pulsar/src/test/java/org/springframework/pulsar/listener/DefaultPulsarMessageListenerContainerTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/listener/DefaultPulsarMessageListenerContainerTxnTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/listener/PulsarListenerTxnTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/listener/PulsarTxnTestsBase.java, spring-pulsar/src/test/java/org/springframework/pulsar/transaction/PulsarTemplateLocalTransactionTests.java
Add transaction support for PulsarTemplate and PulsarListener.
cc: @jonas-grgt 
See #27
=> Add transaction support

gradle/libs.versions.toml
=> Update to Spring Framework 6.1.6

gradle/libs.versions.toml, spring-pulsar/src/test/java/org/springframework/pulsar/listener/PulsarListenerTxnTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/listener/PulsarTxnTestsBase.java
=> Update to Reactor 2023.0.5

spring-pulsar-test/src/main/java/org/springframework/pulsar/test/support/PulsarTestContainerSupport.java
=> Rename PulsarTestContainerSupport#stopContainer2 to stopContainer

gradle/libs.versions.toml
=> Update Pulsar Client Reactive to 0.5.4

spring-pulsar/src/main/java/org/springframework/pulsar/listener/DefaultPulsarMessageListenerContainer.java, spring-pulsar/src/test/java/org/springframework/pulsar/core/PulsarTemplateLocalTransactionTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/listener/DefaultPulsarMessageListenerContainerTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/listener/DefaultPulsarMessageListenerContainerTxnTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/listener/PulsarListenerTxnTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/listener/PulsarTxnTestsBase.java, spring-pulsar/src/test/java/org/springframework/pulsar/listener/TransactionSettingsTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/transaction/PulsarResourceHolderTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/transaction/PulsarResourceSynchronizationTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/transaction/PulsarTransactionManagerTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/transaction/PulsarTransactionUtilsTests.java
=> Add transaction related tests

spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/pulsar/preface.adoc, spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/pulsar/quick-tour.adoc, spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/reactive-pulsar/reactive-quick-tour.adoc
=> [Docs] Correct artifact id for Pulsar starter

spring-pulsar-docs/src/main/antora/modules/ROOT/nav.adoc, spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/pulsar/transactions.adoc
Resolves #660
Best way to review...
Pull down locally and follow https://github.com/spring-projects/spring-pulsar/wiki/Working-with-the-Code#updating-the-reference-documentation
=> Add docs for transaction support

spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/listener/ReactivePulsarListenerTests.java, spring-pulsar/src/test/java/org/springframework/pulsar/listener/PulsarListenerTests.java
Removes duplicated test objects User/User2 and replaces with test objects UserPojo/UserRecord from spring-pulsar-test
=> Use test objects from spring-pulsar-test

build.gradle, settings.gradle
* Replaces `com.gradle.enterprise:3.16.2` with `com.gradle.develocity:3.17.2`
* Updates `io.spring.ge.conventions` to 0.0.17
* Updates deprecated usages of previous Enterprise plugin
=> Migrate to Gradle Develocity plugin

spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/pulsar/pulsar-client.adoc
=> Add doc for auto cluster-level failover

spring-pulsar-docs/src/main/antora/antora-playbook.yml
=> Update antora-ui-spring to `v0.4.14` (1.0.x)

spring-pulsar-docs/src/main/antora/antora-playbook.yml
=> Update antora-ui-spring to `v0.4.14` (1.1.x)

gradle.properties
=> [Release 1.0.7] Update version

.gitignore, gradle/antora-docs.gradle, settings.gradle, spring-pulsar-docs/package.json, spring-pulsar-docs/src/main/antora/antora-playbook.yml, src/nohttp/suppressions.xml
=> Use Algolia extension

gradle/antora-docs.gradle, spring-pulsar-docs/src/main/antora/modules/ROOT/pages/attributes/attributes-variables.adoc
Prior to this commit, the version number used in the Pulsar docs link was hardcoded to `3.2.x`. Now the version number is derived from the Pulsar client lib version specified in libs.version.toml.
=> Use dynamic version for Pulsar docs link

spring-pulsar-docs/src/main/antora/modules/ROOT/pages/whats-new.adoc, spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarTopic.java, spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarTopicBuilder.java, spring-pulsar/src/test/java/org/springframework/pulsar/core/PulsarTopicBuilderTests.java
=> Allow PulsarTopicBuilder#init null values

gradle/libs.versions.toml
=> Update Reactor to 2024.0.0-M5

gradle/libs.versions.toml
=> Update Reactor to `2024.0.0-M6`

.github/dco.yml, CODE_OF_CONDUCT.adoc, CONTRIBUTING.adoc
=> ⚠️ DO NOT MERGE ⚠️ Update from CLA to DCO

.github/dco.yml, CODE_OF_CONDUCT.adoc, CONTRIBUTING.adoc
=> ⚠️ DO NOT MERGE ⚠️ Update from CLA to DCO (1.0.x)

gradle/libs.versions.toml
=> Update Spring framework to 6.1.19

gradle/libs.versions.toml
=> Update Pulsar Client Reactive to 0.6.0

spring-pulsar/src/main/java/org/springframework/pulsar/config/AbstractPulsarListenerContainerFactory.java, spring-pulsar/src/main/java/org/springframework/pulsar/config/ConcurrentPulsarListenerContainerFactory.java, spring-pulsar/src/test/java/org/springframework/pulsar/config/ConcurrentPulsarListenerContainerFactoryTests.java
=> [VERIFY] GH-1103

gradle/libs.versions.toml
=> Update pulsar-client-reactive to 0.7.0

gradle/libs.versions.toml
=> Update Spring Framework to 6.2.8

spring-pulsar-docs/src/main/antora/modules/ROOT/pages/appendix/version-compatibility.adoc
=> Update compatability matrix in appendix doc

gradle/libs.versions.toml
=> Update Reactor to 2024.0.7

gradle/java-conventions.gradle, spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/aot/ReactivePulsarRuntimeHints.java, spring-pulsar/src/main/java/org/springframework/pulsar/aot/PulsarRuntimeHints.java
This commit removes/replaces deprecations that were causing the build to fail (i.e. those that were marked for removal).
=> Fix forRemoval deprecations

gradle/libs.versions.toml
=> Update to Spring 7.0.0-M7

gradle/libs.versions.toml
=> Update to Reactor 2025.0.0-M5

gradle/libs.versions.toml
=> Update to Jackson 2.20.0-rc1
