- spring-pulsar-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarAnnotationDrivenConfiguration.java
- spring-pulsar-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/PulsarListenerTests.java
- spring-pulsar/src/main/java/org/springframework/pulsar/annotation/EnablePulsar.java
- spring-pulsar/src/main/java/org/springframework/pulsar/annotation/PulsarBootstrapConfiguration.java
- spring-pulsar/src/main/java/org/springframework/pulsar/annotation/PulsarListener.java
- spring-pulsar/src/main/java/org/springframework/pulsar/annotation/PulsarListenerAnnotationBeanPostProcessor.java
- spring-pulsar/src/main/java/org/springframework/pulsar/annotation/PulsarListenerConfigurer.java
- spring-pulsar/src/main/java/org/springframework/pulsar/annotation/PulsarListeners.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/DefaultPulsarListenerContainerFactory.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/PulsarClientFactoryBean.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/PulsarListenerBeanNames.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/DefaultPulsarProducerFactory.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarProducerFactory.java
- src/api/overview.html
- src/dist/notice.txt
@sobychacko this is the lightweight cleanup/refactorings I did. I wanted to get this smaller "noise" out of the way before the subsequent PR which will contain the heavier changes to the template etc..
> Minor cleanup and refactoring

- spring-pulsar-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/PulsarListenerTests.java
- spring-pulsar-sample-apps/src/main/java/app1/PulsarBootApp.java
- spring-pulsar-sample-apps/src/main/java/app2/ProducerApp.java
- spring-pulsar-sample-apps/src/main/java/app4/FailoverConsumerApp.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/DefaultPulsarProducerFactory.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarOperations.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarProducerFactory.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarTemplate.java
This proposal does the following (reason in sub-bullets):
* Introduces a PulsarOperations interface
* matches spring-kafka and defines contract
* provides default delegation methods to avoid cookie cutter code in impl
* Removes producer caching from PulsarTemplate (will add this back in on follow commit but probably in producer factory)
* Current caching is danger of OOME (no cleaning of cache)
* Producer factory no longer holds onto a single producer instance
* we hand out N of these, if anything we should hold reference to all and close etc..
* Removes defaultClientName from PulsarTemplate
* not thread-safe (topic set on producer config in producer factory)
* misleading API and it mutates the config props (I never liked this about KafkaTemplate)
* PulsarClient holds onto all Producers …
> Refactor template/producer to not use default topic name

- build.gradle
- spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarOperations.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarTemplate.java
- spring-pulsar/src/test/java/org/springframework/pulsar/core/PulsarProducerFactoryTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/core/PulsarTemplateTests.java
- src/checkstyle/checkstyle.xml
This adds tests cases for the newly added `PulsarOperations` APIs.
> Add test cases to PulsarTemplateTests

- README.adoc
This PR fixes some minor issues in the README, such as control characters, doubles, and incorrect information
> [hotfix] Fix README

- build.gradle
The `zip.deployed=false, zip.type=docs` needs to be set in order for the docs to get auto-deployed to static.spring.io
> Add required props to published docs

- CODE_OF_CONDUCT.adoc
- CONTRIBUTING.adoc
- LICENSE.txt
- README.adoc
Removes the redundant details from README that are now in the ref docs. Also adds basic contributing, code of conduct, etc..
> Add basic docs

- buildSrc/src/main/java/org/springframework/pulsar/gradle/docs/asciidoc/AsciidoctorConventionsPlugin.java
- buildSrc/src/main/java/org/springframework/pulsar/gradle/docs/configprops/ConfigurationPropertiesPlugin.java
- buildSrc/src/main/java/org/springframework/pulsar/gradle/docs/configprops/DocumentConfigurationProperties.java
- spring-pulsar-docs/src/main/asciidoc/application-properties.adoc
- spring-pulsar-docs/src/main/asciidoc/index.adoc
- spring-pulsar-docs/src/main/asciidoc/preface.adoc
- spring-pulsar-docs/src/main/asciidoc/pulsar.adoc
- spring-pulsar-docs/src/main/asciidoc/quick-tour.adoc
- spring-pulsar-sample-apps/src/main/java/app1/SpringPulsarBootApp.java
- spring-pulsar-sample-apps/src/main/java/app2/FailoverConsumerApp.java
- Remove hardcoded code where possible
- Link to auto-generated config props rather than hardcoded tables
- Simplify some wording
@sobychacko I still need to do the "Producer Factory Caching" and will do that tomorrow am. But I wanted to get this round of mods out there asap. 
If you want to view the output locally then do these steps:
- Run `./gradlew clean build -x test` from the root dir
- Navigate to `./spring-pulsar-docs/build/docs/asciidocMultipage/pulsar.html`
- Click Preview button in IDEA or open directly in browser
I think you will like what you see. 
ℹ️ the next thing we need to do is pull the inline code in the doc out into the `docs/src` where possible and include source for the bigger examples. Otherwise it will get stale quickly.
> Polish reference docs

- buildSrc/src/main/java/org/springframework/pulsar/gradle/docs/configprops/DocumentConfigurationProperties.java
- spring-pulsar-docs/src/main/asciidoc/application-properties.adoc
- spring-pulsar-docs/src/main/asciidoc/pulsar.adoc
- spring-pulsar-sample-apps/src/main/java/app1/SpringPulsarBootApp.java
- spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarAutoConfiguration.java
- spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarProperties.java
- spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/PulsarAutoConfigurationTests.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarAdministration.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarTopic.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/PulsarContainerProperties.java
- spring-pulsar/src/test/java/org/springframework/pulsar/core/PulsarAdministrationTests.java
This PR adds auto-configuration and documentation for #64.
> Followup "GH-41 Add auto-created topics"

- spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/AbstractContainerBaseTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/core/AbstractContainerBaseTests.java
This is a best-effort solution for issue #57.
It uses the JVMs system properties to detect the M1 architecture.
This solution will fail if the JVM is running through Rosetta emulation. Other approaches that are independent of the JVM suffer similar problems (see [this question about detecting the M1 from the cli](https://stackoverflow.com/questions/65259300/detect-apple-silicon-from-command-line) for example) so I believe there is no really good solution for this edge case.
> Detect M1 mac in test and substitute container image (#57)

- spring-pulsar-docs/src/main/asciidoc/pulsar.adoc
This PR fixes the sections in the documentation.
Currently, everything from 'Intercepting' messages is a separate section instead of being included in 'Using Spring for Apache Pulsar' as seen here:
> Fix documentation sections

- spring-pulsar/src/main/java/org/springframework/pulsar/listener/AbstractPulsarMessageListenerContainer.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/DefaultPulsarConsumerErrorHandler.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/DefaultPulsarMessageListenerContainer.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/PulsarBatchListenerFailedException.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/PulsarBatchMessageListener.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/PulsarConsumerErrorHandler.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/PulsarDeadLetterPublishingRecoverer.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/PulsarMessageRecoverer.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/PulsarMessageRecovererFactory.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/adapter/PulsarBatchMessagingMessageListenerAdapter.java
- spring-pulsar/src/main/java/org/springframework/pulsar/support/converter/PulsarBatchMessageConverter.java
- spring-pulsar/src/main/java/org/springframework/pulsar/support/converter/PulsarBatchMessagingMessageConverter.java
- spring-pulsar/src/test/java/org/springframework/pulsar/core/ConsumerAcknowledgmentTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/DefaultPulsarConsumerErrorHandlerTests.java
Provide a Spring specific general mechanism to handle consumer errors regardless of the subscription type. Currently for exclusive and failover subscriptions, Pulsar Java client does not allow the applicaitons to use a DLQ. This feature allows the applications to set a PulsarConsumerErrorHandler that takes a Backoff and PulsarMessageRecoverer to retry and recover the failed message.
This is an initial commit for this feature and more changes in this area will follow.
Resolves https://github.com/spring-projects-experimental/spring-pulsar/issues/28
> Introducing experimental consumer error handling

- spring-pulsar-docs/src/main/asciidoc/quick-tour.adoc
> Add snapshot/milestone dep info to ref docs

- spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/PulsarAutoConfigurationTests.java
- spring-pulsar/src/main/java/org/springframework/pulsar/annotation/PulsarListener.java
- spring-pulsar/src/main/java/org/springframework/pulsar/annotation/PulsarListenerAnnotationBeanPostProcessor.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/MethodPulsarListenerEndpoint.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/AbstractPulsarMessageListenerContainer.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/ConcurrentPulsarMessageListenerContainer.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/PulsarMessageListenerContainer.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/ConcurrentPulsarMessageListenerContainerTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/PulsarListenerTests.java
This PR introduces the ability for PulsarListener annotation to provide the name of the PulsarConsumerErrorHandler bean. When such a bean name is provided, the framework properly scans for the bean and delegates it to downstream message listener container.
> More Pulsar Consumer Error handling Changes

- spring-pulsar-dependencies/build.gradle
- spring-pulsar-sample-apps/build.gradle
- spring-pulsar-spring-boot-autoconfigure/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/SpringPulsarBootAppSanityTests.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/DefaultPulsarMessageListenerContainer.java
- Made the following TEMPORARY changes to appease downgrading to SB/SF milestones:
- Removed `AsynTaskExecutor.submitCompletable` (only in SF snaphot)
- Revert b188436ab5db56faf713d39593a67e2999864c2e (auto-generated auto-config imports file only in SB snapshot)
- Added SpringBootTest sanity test to catch when auto-config is not in place.
@alpreu @sobychacko
> Use SB/SF milestone libs for M1 release

- spring-pulsar/src/main/java/org/springframework/pulsar/annotation/PulsarListener.java
- spring-pulsar/src/main/java/org/springframework/pulsar/annotation/PulsarListenerAnnotationBeanPostProcessor.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/MethodPulsarListenerEndpoint.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/DefaultPulsarConsumerFactory.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/AbstractPulsarMessageListenerContainer.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/ConcurrentPulsarMessageListenerContainer.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/DefaultPulsarMessageListenerContainer.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/PulsarMessageListenerContainer.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/ConcurrentPulsarMessageListenerContainerTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/PulsarListenerTests.java
Provide a way to specify ackTimeoutRedeliveryBackoff through PulsarListener annotation.
These changes are similar to the one in which we introduced negativeAckRedeliveryBackoff: https://github.com/spring-projects-experimental/spring-pulsar/commit/cc3842062e970ae4b64ade537d085bd0ec309ac9
> AckTimeout Redlivery Backoff Changes

- spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarAnnotationDrivenConfiguration.java
- spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarProperties.java
- spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/PulsarAutoConfigurationTests.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/DefaultPulsarMessageListenerContainer.java
> Listener container properties for batch receive.

- spring-pulsar-docs/src/main/asciidoc/pulsar.adoc
- spring-pulsar-sample-apps/src/main/java/app2/FailoverConsumerApp.java
- spring-pulsar/src/main/java/org/springframework/pulsar/annotation/PulsarListener.java
- spring-pulsar/src/main/java/org/springframework/pulsar/annotation/PulsarListenerAnnotationBeanPostProcessor.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/PulsarListenerTests.java
**NOTE** I also took the liberty of simplifying some `if/else/return` blocks and moving `.collect(Collectors.toList()) -> `toList()`.
> Use enum for PulsarListener subscriptionType

- spring-pulsar-docs/src/main/asciidoc/pulsar.adoc
Adding docs dor concurrency
Cleaning up docs on using Acknowledgment API
> Listener docs cleanup

- spring-pulsar/src/main/java/org/springframework/pulsar/listener/DefaultPulsarMessageListenerContainer.java
- More controlled access to ContainerProperties in the listener
- Concurrency related cleanup in retrying code
Resovles https://github.com/spring-projects-experimental/spring-pulsar/issues/133
> Code cleanup in message listener container

- spring-pulsar/src/main/java/org/springframework/pulsar/config/MethodPulsarListenerEndpoint.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/adapter/PulsarBatchMessagingMessageListenerAdapter.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/adapter/PulsarMessagingMessageListenerAdapter.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/adapter/PulsarRecordMessagingMessageListenerAdapter.java
- spring-pulsar/src/main/java/org/springframework/pulsar/support/DefaultPulsarMessageHeaderMapper.java
- spring-pulsar/src/main/java/org/springframework/pulsar/support/PulsarHeaders.java
- spring-pulsar/src/main/java/org/springframework/pulsar/support/PulsarMessageHeaderMapper.java
- spring-pulsar/src/main/java/org/springframework/pulsar/support/converter/PulsarMessagingMessageConverter.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/PulsarListenerTests.java
Convert Pulsar Message metadata as PulsarHeaders and make them available on PulsarListener through Spring's @Header annotation.
Resolves https://github.com/spring-projects-experimental/spring-pulsar/issues/150
> Support Pulsar Headers

- spring-pulsar-dependencies/build.gradle
- spring-pulsar-spring-boot-autoconfigure/src/test/resources/application.yml
- spring-pulsar/build.gradle
This PR replaces the many manual entries in the `spring-pulsar-dependencies` Gradle Java Platform.
All removed dependencies are covered by the SB BOM and were previously using the same exact version as in the SB BOM. We had to manually keep these in sync and it was toil. 
@sobychacko  This does not force SB on Spring Pulsar users as it is an internal project detail only.
Further reduces the test logging output
> Use SpringBoot dependencies for version constraints

- buildSrc/src/main/java/org/springframework/pulsar/gradle/docs/configprops/DocumentConfigurationProperties.java
- spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarAnnotationDrivenConfiguration.java
- spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarAutoConfiguration.java
- spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarProperties.java
- spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/PulsarAutoConfigurationTests.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/AbstractPulsarListenerContainerFactory.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/ConcurrentPulsarListenerContainerFactory.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/MethodPulsarListenerEndpoint.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarTemplate.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/AbstractPulsarMessageListenerContainer.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/ConcurrentPulsarMessageListenerContainer.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/DefaultPulsarMessageListenerContainer.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/PulsarContainerProperties.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/ConcurrentPulsarMessageListenerContainerTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/PulsarListenerTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/observation/ObservationIntegrationTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/observation/ObservationTests.java
Adds auto-configuration of the observation aspects of the listener and template. 
* I refactored the template and listeners to use immutable constructors for some key pieces to simplify them as well as make them auto-configuration friendly (eg. the auto-config will/not pass in the observation registry when user has disabled the obeservations property).
Resolves #147
> Add observations auto-configuration

- spring-pulsar/src/main/java/org/springframework/pulsar/listener/ConcurrentPulsarMessageListenerContainer.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/DefaultPulsarMessageListenerContainer.java
- spring-pulsar/src/test/java/org/springframework/pulsar/observation/ObservationIntegrationTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/observation/ObservationTests.java
Some strange timing going on w/ redelivery of messages across tracing setup runs in ObservationIntegrationTests. Lets see how this change works in CI.
> Enable observations tests

- spring-pulsar/src/main/java/org/springframework/pulsar/core/reactive/DefaultReactivePulsarSenderFactory.java
- spring-pulsar/src/test/java/org/springframework/pulsar/core/reactive/DefaultReactiveMessageSenderFactoryTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/core/reactive/ReactivePulsarTemplateTests.java
Also refactored DefaultReactiveMessageSenderFactoryTests because it was mocking inside the reactive client and it's never a good idea to mock inside your dependencies.
> Add cache to DefaultReactivePulsarSenderFactory

- spring-pulsar/src/main/java/org/springframework/pulsar/core/reactive/DefaultReactivePulsarSenderFactory.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/reactive/ReactivePulsarSenderFactory.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/reactive/ReactivePulsarSenderOperations.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/reactive/ReactivePulsarSenderTemplate.java
- spring-pulsar/src/test/java/org/springframework/pulsar/core/reactive/DefaultReactiveMessageSenderFactoryTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/core/reactive/ReactivePulsarTemplateTests.java
* Ensure DefaultReactivePulsarSenderFactory is not null
* Simplify API naming
* Remove MessageRouter specific methods as it can be configured in the ReactiveMessageSenderSpec (which is not the case in the imperative Producer conf properties)
> Rework reactive sender factory

- spring-pulsar/src/test/java/org/springframework/pulsar/core/reactive/DefaultReactiveMessageConsumerFactoryTests.java
DO NOT MERGE: For discussion only.
@cbornet I was going to add a polish commit to recently merged PR (see [comment](https://github.com/spring-projects-experimental/spring-pulsar/pull/178#discussion_r1008572835)). However, when doing so I figured I wanted to run both of these styles by you before pushing a commit on top of yours w/o your approval / review. 
I wanted to add coverage for the case where the RPCF was created w/ a null spec. It basically doubles the test methods such that we check both `createConsumer()` w/ customizer and w/o customizer on both factories (one created w/ spec and one created w/o spec). 
I did it 2 ways in this proposal - w/ and w/o the use of `@Nested`. Which do you prefer? Or, would a single test just verifying the `<init> w/ null spec` be sufficient?
> Add tests to DefaultReactiveMessageConsumerFactoryTests (#185)

- spring-pulsar-docs/src/main/asciidoc/pulsar.adoc
- spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarAnnotationDrivenConfiguration.java
- spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarProperties.java
- spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/PulsarAutoConfigurationTests.java
> Use Duration, DataSize and boxed types in PulsarProperties

- spring-pulsar/src/main/java/org/springframework/pulsar/core/ConsumerBuilderConfigurationUtil.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/ConsumerBuilderCustomizer.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/DefaultPulsarConsumerFactory.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarConsumerFactory.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/DefaultPulsarMessageListenerContainer.java
- spring-pulsar/src/test/java/org/springframework/pulsar/core/ConsumerBuilderConfigurationUtilTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/ConcurrentPulsarMessageListenerContainerTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/DefaultPulsarMessageListenerContainerTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/PulsarListenerTests.java
This PR is https://github.com/spring-projects-experimental/spring-pulsar/pull/188 with an additional collaboration commit to reduce the amount of mapping required in DPMLC. 
cc: @cbornet @sobychacko
> [Collaborated] Use type safe structures to configure the consumer 

- spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarProperties.java
- spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/PulsarPropertiesTests.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarAdministration.java
- spring-pulsar/src/test/java/org/springframework/pulsar/core/PulsarAdministrationTests.java
- src/checkstyle/checkstyle.xml
This code proposal provides a workaround for the fact that the PulsarAdminBuilder does not respect the auth properties specified in the config map during a `loadConf`. 
* Commit 1: add test to show the breakage
* Commit 2: fix the breakage
* Commit 3: fix unrelated issue in properties assertion
* Submit fix to Apache Pulsar
Fixes #194
> PulsarAdministration now respects auth properties

- spring-pulsar-docs/src/main/asciidoc/application-properties.adoc
- spring-pulsar-docs/src/main/asciidoc/authentication.adoc
- spring-pulsar-docs/src/main/asciidoc/index.adoc
- spring-pulsar-docs/src/main/asciidoc/preface.adoc
- spring-pulsar-docs/src/main/asciidoc/pulsar.adoc
- spring-pulsar-docs/src/main/asciidoc/quick-tour.adoc
for grammar, usage, voice, spelling, and tense.
Also added some cross-references and, per my conversation with Chris Bono, removed some includes.
> Editing pass

- spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/PulsarListenerTests.java
- spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/ReactivePulsarListenerTests.java
PulsarListenerTests
- simplify assert usage
- remove finals
ReactivePulsarListenerTests
- simplify assert usage
- remove finals
- remove allowCircularReferences
> [run-tests] Test polishing

- spring-pulsar/src/main/java/org/springframework/pulsar/annotation/ReactivePulsarListener.java
- spring-pulsar/src/main/java/org/springframework/pulsar/annotation/ReactivePulsarListenerAnnotationBeanPostProcessor.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/reactive/AbstractReactivePulsarListenerEndpoint.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/reactive/DefaultReactivePulsarListenerContainerFactory.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/reactive/ReactivePulsarListenerEndpoint.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/reactive/ReactivePulsarListenerEndpointAdapter.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/reactive/DefaultReactivePulsarMessageListenerContainer.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/reactive/ReactivePulsarContainerProperties.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/reactive/DefaultReactivePulsarMessageListenerContainerTests.java
There is no real use for this as the number of messages pulled is already capped by concurrency*32 (default prefetch of flatMap). 
maxInFlight may be removed from the reactive client
> Remove maxInFlight

- spring-pulsar/src/main/java/org/springframework/pulsar/annotation/PulsarListenerAnnotationBeanPostProcessor.java
- spring-pulsar/src/main/java/org/springframework/pulsar/annotation/ReactivePulsarListenerAnnotationBeanPostProcessor.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/MethodPulsarListenerEndpoint.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/reactive/MethodReactivePulsarListenerEndpoint.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/CachingPulsarProducerFactory.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarTemplate.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/reactive/DefaultReactivePulsarSenderFactory.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/reactive/ReactivePulsarTemplate.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/DefaultPulsarConsumerErrorHandler.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/DefaultPulsarMessageListenerContainer.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/adapter/PulsarBatchMessagingMessageListenerAdapter.java
- spring-pulsar/src/main/java/org/springframework/pulsar/support/converter/PulsarMessagingMessageConverter.java
- spring-pulsar/src/test/java/org/springframework/pulsar/core/ConsumerAcknowledgmentTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/core/FailoverConsumerTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/DefaultPulsarConsumerErrorHandlerTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/DefaultPulsarMessageListenerContainerTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/PulsarListenerTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/reactive/ReactivePulsarListenerTests.java
As per https://github.com/spring-projects-experimental/spring-pulsar/pull/188#discussion_r1011149565
> Remove final keyword in methods

- spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarProperties.java
- spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarReactiveProperties.java
`initialSubscriptionName` is an internal param used by the Pulsar client for DLT. It is not used in the reactive client and should be removed from `MutableReactiveMessageSenderSpec`
> Remove initialSubscriptionName from sender properties

- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/listener/adapter/PulsarReactiveMessagingMessageListenerAdapter.java
- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/listener/adapter/PulsarReactiveOneByOneMessagingMessageListenerAdapter.java
- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/listener/adapter/PulsarReactiveStreamingMessagingMessageListenerAdapter.java
- spring-pulsar/build.gradle
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/adapter/PulsarMessagingMessageListenerAdapter.java
This pulls the usage of `Flux` out of the base messaging adapter now that we have split the modules imperative/reactive. 
NOTE: The split is a bit contrived but will require more rework on the logic in the base adapter to make it more natural.
> Extract Flux from base messaging adapter

- spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarReactiveProperties.java
- spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/PulsarReactivePropertiesTests.java
Also removing `KeySharedMode` for now as `KeySharedPolicySticky` needs a param to configure `Ranges`  otherwise it fails. This can be added again later by adding support for ranges.
> Add more settings to Consumer in PulsarReactiveProperties

- spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarProperties.java
- spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/PulsarPropertiesTests.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarAdministration.java
PATL @cbornet @sobychacko 
Fixes #239
> Fix admin props failing on duration types

- spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarProperties.java
- spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/PulsarPropertiesTests.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarAdministration.java
The 2.12 Pulsar client will handle the autoCertRefreshTime in CCD but the property will be named `autoCertRefreshSeconds`
> Change autoCertRefreshTimeMs to autoCertRefreshSeconds

- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/config/annotation/ReactivePulsarListenerAnnotationBeanPostProcessor.java
- spring-pulsar/src/main/java/org/springframework/pulsar/annotation/PulsarListenerAnnotationBeanPostProcessor.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/PulsarListenerEndpointRegistrar.java
- Remove custom argument resolvers from PulsarListenerEndpointRegistrar, as this is an un-used feature at the moment.
- The default HandlerMethodArgumentResolver is capable of adapting the all the method arguments in all the PulsarListener use cases we encountered so far. We will add it back if custom argument resolution is necessary.
> Remove custom argument resolvers

- spring-pulsar-docs/src/main/asciidoc/application-properties.adoc
- spring-pulsar-docs/src/main/asciidoc/attributes.adoc
- spring-pulsar-docs/src/main/asciidoc/authors.adoc
- spring-pulsar-docs/src/main/asciidoc/copyright.adoc
- spring-pulsar-docs/src/main/asciidoc/index.adoc
- spring-pulsar-docs/src/main/asciidoc/intro.adoc
- spring-pulsar-docs/src/main/asciidoc/non-ga-versions.adoc
- spring-pulsar-docs/src/main/asciidoc/observability.adoc
- spring-pulsar-docs/src/main/asciidoc/preface.adoc
- spring-pulsar-docs/src/main/asciidoc/pulsar-admin.adoc
- spring-pulsar-docs/src/main/asciidoc/pulsar.adoc
- spring-pulsar-docs/src/main/asciidoc/quick-tour.adoc
- spring-pulsar-docs/src/main/asciidoc/reactive-pulsar.adoc
- spring-pulsar-docs/src/main/asciidoc/reactive-quick-tour.adoc
- spring-pulsar-sample-apps/sample-app1/build.gradle
- spring-pulsar-sample-apps/sample-app2/build.gradle
- spring-pulsar-sample-apps/sample-reactive/build.gradle
> Add reactive docs

- .github/workflows/ci-pr.yml
- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/config/MethodReactivePulsarListenerEndpoint.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/MethodPulsarListenerEndpoint.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/DefaultSchemaResolver.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/SchemaResolver.java
- spring-pulsar/src/test/java/org/springframework/pulsar/core/DefaultSchemaResolverTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/PulsarListenerTests.java
Removes the schema mapping code out of the method listener endpoints and into the SchemaResolver. 
See #269
> Listener endpoints use schema resolver

- spring-pulsar-docs/src/main/asciidoc/schema-info/schema-info-template.adoc
- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/core/ReactiveMessageSenderUtils.java
- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/core/ReactivePulsarOperations.java
- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/core/ReactivePulsarTemplate.java
- spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/core/ReactivePulsarTemplateTests.java
- spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/listener/ReactivePulsarListenerTests.java
- spring-pulsar-sample-apps/sample-app1/src/main/java/app1/SpringPulsarBootApp.java
- spring-pulsar-sample-apps/sample-reactive/src/main/java/org.springframework.pulsar.example/ReactiveSpringPulsarBootApp.java
- spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/PulsarListenerTests.java
- spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/ReactivePulsarListenerTests.java
- spring-pulsar-spring-cloud-stream-binder/src/main/java/org/springframework/pulsar/spring/cloud/stream/binder/PulsarMessageChannelBinder.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarOperations.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarTemplate.java
- spring-pulsar/src/test/java/org/springframework/pulsar/core/PulsarTemplateTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/PulsarListenerTests.java
For both PulsarTemplate and ReactivePulsarTemplate:
* remove setSchema()
* add schema param in simple API
* add schema param in fluent API
Update all tests and samples accordingly
See #268
> Remove setSchema API from templates

- spring-pulsar/src/main/java/org/springframework/pulsar/listener/DefaultPulsarMessageListenerContainer.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/DefaultPulsarMessageListenerContainerTests.java
* When container is paused, ensure that we are not spinning CPU cycles by constantly trying to poll in a loop. When pausing the container, the polling waits until a condition is signaled by resuming.
Resolves https://github.com/spring-projects-experimental/spring-pulsar/issues/297
> Container pause/resume improvements

- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/core/DefaultReactivePulsarSenderFactory.java
- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/core/ReactivePulsarSenderFactory.java
- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/core/ReactivePulsarTemplate.java
- spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/core/DefaultReactiveMessageSenderFactoryTests.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/CachingPulsarProducerFactory.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/DefaultPulsarProducerFactory.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarProducerFactory.java
- spring-pulsar/src/test/java/org/springframework/pulsar/core/CachingPulsarProducerFactoryTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/core/PulsarProducerFactoryTests.java
- Add producer/sender factory createSender API w/ only a schema
- Add producer/sender factory createSender API w/ single customizer
- ReactivePulsarSenderFactory createSender API consistent with PulsarProducerFactory createProducer API
- Cleanup/refactor producer factory tests
Resolves #295
> Don't allow topic to be set via customizers

- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/core/DefaultReactivePulsarSenderFactory.java
- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/core/ReactivePulsarOperations.java
- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/core/ReactivePulsarTemplate.java
- spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/core/ReactivePulsarTemplateTests.java
- spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/listener/DefaultReactivePulsarMessageListenerContainerTests.java
In `doSendMany`, when we don't have an explicit Schema or topic, instead of using `sendOne` and create a sender for each message, we can use `switchOnFirst` to build the sender from the first message.
This has the following advantages:
* Can be used for both Schema and topic inference (currently only schema was supported with the sendOne workaround)
* Only one sender is created so the order is preserved even if there is no producer cache configured.
* We can remove `SendMessageBuilder::newMessages(Publisher<T>, Class<T> messageType)` as we get the messageType from the first message.
> Use switchOnFirst to determine the Schema and topic from the first message in doSendMany

- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/core/ReactivePulsarOperations.java
- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/core/ReactivePulsarTemplate.java
- spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/core/ReactivePulsarTemplateTests.java
This way, if you use `newMessage`, you'll have `withMessageCustomizer ` and `send` returns a `Mono`.
Otherwise if you use `newMessages`, `send` returns a `Flux` (`sendMany` is renamed as `send` since there is no more name conflict)
> Make SendMessageBuilder interface more navigable

- spring-pulsar/src/test/java/org/springframework/pulsar/core/SharedSubscriptionConsumerTests.java
Resolves https://github.com/spring-projects-experimental/spring-pulsar/issues/305
> Tests for shared subscriptions

- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/core/DefaultReactivePulsarSenderFactory.java
- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/core/ReactivePulsarSenderFactory.java
- spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/core/DefaultReactiveMessageSenderFactoryTests.java
Removes the `createProducer/Sender(Schema)` as it is likely not that useful as most users will specify a topic and not rely on the default topic. 
The thinking is that the `Reactive/PulsarTemplate` will be the users primary sending API. The producer/sender API is therefore secondary in that sense. This allows us to limit the producer/sender API surface area and remove any questionable APIs in `1.0.0` and let users drive the shape of the API `post-1.0.0`.
Additionally:
* Consistency: A goal is to keep the imperative and reactive producer/sender consistent (as much as possible). I already did this same change to the imperative PPF.  This PR applies the same treatment to the Reactive counterpart.
cc: @cbornet if you agree (don't have an issue w/ this approach) I am planning on removing the …
> Trim ReactivePulsarSenderFactory API

- buildSrc/src/main/java/org/springframework/pulsar/gradle/docs/configprops/DocumentConfigurationProperties.java
- spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarProperties.java
- spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/PulsarPropertiesTests.java
> Pulsar Reader (imperative) Boot properties support

- spring-pulsar/src/main/java/org/springframework/pulsar/core/DefaultPulsarConsumerFactory.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarConsumerFactory.java
- spring-pulsar/src/test/java/org/springframework/pulsar/core/DefaultPulsarConsumerFactoryTests.java
Adding back in the "all required args + single customizer" API variant as this:
1. can be useful when user wants to modify something simple and not provide enc keys and list of customizers
2. consistent w/ sender/producer single customizer APIs
3. compromise of only providing a single API that has all required params
> Add single customizer API in PulsarConsumerFactory

- spring-pulsar-docs/src/main/asciidoc/schema-info/schema-info-listener.adoc
- spring-pulsar-docs/src/main/asciidoc/schema-info/schema-info-template.adoc
- spring-pulsar/src/main/java/org/springframework/pulsar/core/DefaultSchemaResolver.java
- spring-pulsar/src/test/java/org/springframework/pulsar/core/DefaultSchemaResolverTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/core/PulsarTemplateTests.java
> Use Schema.JSON instead of Schema.BYTES as default schema

- spring-pulsar-dependencies/build.gradle
- spring-pulsar-spring-cloud-stream-binder/build.gradle
- spring-pulsar-spring-cloud-stream-binder/src/main/java/org/springframework/pulsar/spring/cloud/stream/binder/PulsarMessageChannelBinder.java
- spring-pulsar-spring-cloud-stream-binder/src/test/java/org/springframework/pulsar/spring/cloud/stream/binder/AbstractPulsarTestBinder.java
- spring-pulsar-spring-cloud-stream-binder/src/test/java/org/springframework/pulsar/spring/cloud/stream/binder/PulsarBinderTests.java
- spring-pulsar-spring-cloud-stream-binder/src/test/java/org/springframework/pulsar/spring/cloud/stream/binder/PulsarTestBinder.java
* Ensuring that AbstractBinderTests and Partition capable tests work for Pulsar binder. Some tests needed to be overridden in order for them to work in a Pulsar context.
* Do not poll the consumer if it is not connected.
Resolves https://github.com/spring-projects-experimental/spring-pulsar/issues/334
> Basic binder compatibility tests

- spring-pulsar-spring-cloud-stream-binder/src/main/java/org/springframework/pulsar/spring/cloud/stream/binder/properties/PulsarBinderConfigurationProperties.java
- spring-pulsar-spring-cloud-stream-binder/src/main/java/org/springframework/pulsar/spring/cloud/stream/binder/properties/PulsarConsumerProperties.java
- spring-pulsar-spring-cloud-stream-binder/src/main/java/org/springframework/pulsar/spring/cloud/stream/binder/properties/PulsarProducerProperties.java
- spring-pulsar-spring-cloud-stream-binder/src/main/java/org/springframework/pulsar/spring/cloud/stream/binder/provisioning/PulsarTopicProvisioner.java
- spring-pulsar-spring-cloud-stream-binder/src/test/java/org/springframework/pulsar/spring/cloud/stream/binder/PulsarBinderConfigurationPropertiesTests.java
- spring-pulsar-spring-cloud-stream-binder/src/test/java/org/springframework/pulsar/spring/cloud/stream/binder/PulsarTopicProvisionerTests.java
In Pulsar, partitioned topics are optional. If we set the default partition count to be 1, then it unnecessarily creates a partitoned topic. Therefore, we need to set the default partition count as 0 in the binder and extended binding properties.
> Pulsar binder partition count defaults

- spring-pulsar/src/main/java/org/springframework/pulsar/core/DefaultPulsarReaderFactory.java
- spring-pulsar/src/main/java/org/springframework/pulsar/event/ReaderFailedToStartEvent.java
- spring-pulsar/src/main/java/org/springframework/pulsar/event/ReaderStartedEvent.java
- spring-pulsar/src/main/java/org/springframework/pulsar/event/ReaderStartingEvent.java
- spring-pulsar/src/main/java/org/springframework/pulsar/reader/AbstractPulsarReaderListenerContainer.java
- spring-pulsar/src/main/java/org/springframework/pulsar/reader/DefaultPulsarReaderListenerContainer.java
- spring-pulsar/src/main/java/org/springframework/pulsar/reader/PulsarReaderContainerProperties.java
- spring-pulsar/src/main/java/org/springframework/pulsar/reader/PulsarReaderListenerContainer.java
- spring-pulsar/src/test/java/org/springframework/pulsar/core/DefaultPulsarReaderFactoryTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/reader/DefaultPulsarReaderListenerContainerTests.java
Adding the basic foundations for the Pulsar Reader container. This is similar to the message listener container mechanism used in the regular consumer for managing the various lifecycles.
Resovles https://github.com/spring-projects-experimental/spring-pulsar/issues/341
> Container infrastructure for Pulsar Reader

- spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarAdministration.java
- spring-pulsar/src/test/java/org/springframework/pulsar/core/PulsarAdministrationTests.java
* Check if topic exists already for both partitioned and unpartitioned cases prior to creating.
Fixes #266
> Improve topic validation

- spring-pulsar-docs/src/main/asciidoc/index.adoc
- spring-pulsar-docs/src/main/asciidoc/pulsar.adoc
- spring-pulsar-docs/src/main/asciidoc/reactive-pulsar.adoc
- spring-pulsar-docs/src/main/asciidoc/topic-resolution.adoc
Moves the topic resolution from the appendix into an included section in the imperative and reactive pages. 
Each link to the topic resolution in the imperative section links to its included topic resolution section. 
Each link to the topic resolution in the reactive section links to its included topic resolution section.
> [Docs] Move topic resolution out of appendix

- buildSrc/src/main/java/org/springframework/pulsar/gradle/docs/configprops/Snippets.java
- spring-pulsar-spring-cloud-stream-binder/src/main/java/org/springframework/pulsar/spring/cloud/stream/binder/properties/PulsarBinderConfigurationProperties.java
- spring-pulsar-spring-cloud-stream-binder/src/main/java/org/springframework/pulsar/spring/cloud/stream/binder/properties/PulsarBindingProperties.java
- spring-pulsar-spring-cloud-stream-binder/src/main/java/org/springframework/pulsar/spring/cloud/stream/binder/properties/PulsarExtendedBindingProperties.java
- spring-pulsar-spring-cloud-stream-binder/src/main/resources/META-INF/additional-spring-configuration-metadata.json
Extend the base config props doc generation to expand config props in maps.
> Add bindings props to generated docs

- spring-pulsar-spring-cloud-stream-binder/src/main/java/org/springframework/pulsar/spring/cloud/stream/binder/PulsarBinderHeaderMapper.java
- spring-pulsar-spring-cloud-stream-binder/src/main/java/org/springframework/pulsar/spring/cloud/stream/binder/PulsarMessageChannelBinder.java
- spring-pulsar-spring-cloud-stream-binder/src/main/java/org/springframework/pulsar/spring/cloud/stream/binder/config/PulsarBinderConfiguration.java
- spring-pulsar-spring-cloud-stream-binder/src/test/java/org/springframework/pulsar/spring/cloud/stream/binder/PulsarBinderHeaderMapperTests.java
- spring-pulsar-spring-cloud-stream-binder/src/test/java/org/springframework/pulsar/spring/cloud/stream/binder/PulsarBinderIntegrationTests.java
- spring-pulsar/src/main/java/org/springframework/pulsar/support/header/AbstractPulsarHeaderMapper.java
- spring-pulsar/src/main/java/org/springframework/pulsar/support/header/JacksonUtils.java
- spring-pulsar/src/main/java/org/springframework/pulsar/support/header/package-info.java
Add SCSt Pulsar binder specific header mapper that wraps the auto-configured header mapper and removes NEVER binder-specific headers. 
Adds IT tests for the binder complex headers etc..
See #366
> Add SCSt binder specific header mapper

- spring-pulsar-docs/src/main/asciidoc/schema-info/custom-schema-mapping.adoc
- spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarAutoConfiguration.java
- spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarProperties.java
- spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/PulsarAutoConfigurationTests.java
- spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/PulsarPropertiesTests.java
- spring-pulsar-spring-cloud-stream-binder/src/test/java/org/springframework/pulsar/spring/cloud/stream/binder/PulsarBinderIntegrationTests.java
* Remove redundant SchemaInfo.messageType as the key of the type mappings tells us that info
Before this change:
```yaml
spring:
pulsar:
defaults:
type-mappings:
- message-type: com.acme.User
schema-info:
schema-type: AVRO
message-type: com.acme.User
```
After this change: 
```yaml
spring:
pulsar:
defaults:
type-mappings:
- message-type: com.acme.User
schema-info:
schema-type: AVRO
```
> Simplify defaults type mappings

- spring-pulsar/src/main/java/org/springframework/pulsar/aot/PulsarRuntimeHints.java
- Adds native hints to allow the binder to run in a GraalVM native image.
> Add AOT support for Pulsar binder

- spring-pulsar-spring-cloud-stream-binder/src/main/java/org/springframework/pulsar/spring/cloud/stream/binder/PulsarMessageChannelBinder.java
- spring-pulsar-spring-cloud-stream-binder/src/test/java/org/springframework/pulsar/spring/cloud/stream/binder/PulsarExtendedBindingPropertiesTests.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/AbstractPulsarListenerContainerFactory.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/PulsarContainerProperties.java
* If consumer properties are directly overridden, we need to sync that with container properties. This commit tries to centralize this synching.
> Better container properties sync

- spring-pulsar-reactive/build.gradle
- spring-pulsar-spring-boot-autoconfigure/build.gradle
- spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarAutoConfiguration.java
- spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/PulsarAutoConfigurationTests.java
- spring-pulsar-spring-boot-starter/build.gradle
- spring-pulsar/build.gradle
- spring-pulsar/src/main/java/org/springframework/pulsar/core/DefaultSchemaResolver.java
Tightens up some dependencies so that when we move into Spring Boot we do not bring unwanted transitive dependencies etc..
> Dependency hygiene required by Spring Boot

- spring-pulsar-cache-provider-caffeine/build.gradle
- Don't publish rich Gradle module for spring-pulsar-cache-provider-caffeine
> Fix publish for shaded caffeine artifact

- spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarAnnotationDrivenConfiguration.java
- spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarAutoConfiguration.java
- spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/PulsarAutoConfigurationTests.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/AbstractPulsarListenerContainerFactory.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/ConcurrentPulsarListenerContainerFactory.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarTemplate.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/AbstractPulsarMessageListenerContainer.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/ConcurrentPulsarMessageListenerContainer.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/DefaultPulsarMessageListenerContainer.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/PulsarContainerProperties.java
- spring-pulsar/src/test/java/org/springframework/pulsar/core/PulsarTemplateObservationConfigurationTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/core/PulsarTemplateTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/ConcurrentPulsarMessageListenerContainerTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/PulsarListenerTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/observation/ObservationIntegrationTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/observation/ObservationTests.java
* Remove observation registry and convention from constructors on PulsarTemplate and CPLCF
* Lookup observation registry and convention from app context at start time
As described [here](https://github.com/spring-projects/spring-boot/pull/34763#discussion_r1148417303)
> Hide observation API from public API on template and listener

- .github/workflows/ci-pr.yml
- spring-pulsar-spring-boot-autoconfigure/src/main/java/org/springframework/pulsar/autoconfigure/PulsarProperties.java
- spring-pulsar-spring-boot-autoconfigure/src/test/java/org/springframework/pulsar/autoconfigure/PulsarPropertiesTests.java
Add missing tlsCertificateFilePath/tlsKeyFilePath configs which are needed to configure mutual TLS encryption by itself (without authentication plugin).
resolves #374
> Add tlsCertificateFilePath/tlsKeyFilePath config

- spring-pulsar-dependencies/build.gradle
- spring-pulsar-reactive/build.gradle
- use `pulsar-client-reactive-producer-cache-caffeine-shaded`
- exclude `pulsar-client` from reactive client modules as it brings in unwanted transitive deps
> Use shaded cache module for Reactive client

- integration-tests/integration-tests.gradle
- spring-pulsar/spring-pulsar.gradle
- spring-pulsar/src/test/java/org/springframework/pulsar/function/PulsarFunctionAdministrationTests.java
This PR replaces use of Spring Boot test module.
> Remove use of Spring Boot test module

- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/core/DefaultReactivePulsarConsumerFactory.java
- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/core/DefaultReactivePulsarReaderFactory.java
- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/core/DefaultReactivePulsarSenderFactory.java
- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/core/ReactivePulsarSenderFactory.java
- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/core/ReactivePulsarTemplate.java
- spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/core/DefaultReactivePulsarConsumerFactoryTests.java
- spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/core/DefaultReactivePulsarReaderFactoryTests.java
- spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/core/DefaultReactivePulsarSenderFactoryTests.java
- spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/core/ReactivePulsarTemplateTests.java
- spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/listener/DefaultReactivePulsarMessageListenerContainerTests.java
- spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/listener/ReactivePulsarListenerTests.java
* Also add builder to ReactivePulsarSenderFactory
See #432
> Add multi-customizers to reactive reader and consumer

- .github/workflows/ci.yml
- .github/workflows/prepare-release.yml
Update workflows to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow files that use `set-output` command through the following command:
```bash
$ find . -name '*.yml' -o -name '*.yaml' | xargs egrep '\bset-output\b'
```
**AS-IS**
```yaml
echo "::set-output name=project_version::$version"
```
**TO-BE**
```yaml
echo "project_version=$version" >> $GITHUB_OUTPUT
```
> Replace deprecated command with environment file

- spring-pulsar-cache-provider-caffeine/src/main/java/org/springframework/pulsar/cache/provider/caffeine/CaffeineCacheProvider.java
- spring-pulsar-cache-provider-caffeine/src/main/java/org/springframework/pulsar/cache/provider/caffeine/CaffeineCacheProviderFactory.java
- spring-pulsar-cache-provider-caffeine/src/main/resources/META-INF/services/org.springframework.pulsar.cache.provider.CacheProviderFactory
- spring-pulsar-cache-provider-caffeine/src/main/resources/META-INF/services/org.springframework.pulsar.core.CacheProviderFactory
- spring-pulsar-cache-provider/src/main/java/org/springframework/pulsar/cache/provider/CacheProvider.java
- spring-pulsar-cache-provider/src/main/java/org/springframework/pulsar/cache/provider/CacheProviderFactory.java
- spring-pulsar-cache-provider/src/test/java/org/springframework/pulsar/cache/provider/CacheProviderFactoryTests.java
- spring-pulsar-cache-provider/src/test/resources/META-INF/services/org.springframework.pulsar.cache.provider.CacheProviderFactory
- spring-pulsar-cache-provider/src/test/resources/META-INF/services/org.springframework.pulsar.core.CacheProviderFactory
- spring-pulsar/src/main/java/org/springframework/pulsar/core/CachingPulsarProducerFactory.java
- spring-pulsar/src/test/java/org/springframework/pulsar/core/CachingPulsarProducerFactoryTests.java
The cache provider modules source files were previously packaged under the `spring.pulsar.core` name. 
This moves them to a package name that is specific to their module name. 
The motiivation of the change is to pre-emptively reduce confusion w/ the Java module system.
> Move cache provider into proper package.

- gradle.properties
- spring-pulsar-docs/spring-pulsar-docs.gradle
- spring-pulsar-docs/src/main/asciidoc/attributes-variables.adoc
- spring-pulsar-docs/src/main/asciidoc/pulsar-binder.adoc
- spring-pulsar-sample-apps/sample-pulsar-binder/build.gradle
- spring-pulsar-sample-apps/sample-pulsar-functions/sample-signup-app/build.gradle
The Pulsar binder moved from this repo to SCSt repo. This commit updates to use the new Pulsar binder.
> Update Pulsar binder to SCSt 4.1.0-SNAPSHOT

- build.gradle
- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/core/DefaultReactivePulsarSenderFactory.java
- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/core/RestartableComponentSupport.java
- spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/core/DefaultReactivePulsarSenderFactoryTests.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/CachingPulsarProducerFactory.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/DefaultPulsarClientFactory.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/ProducerUtils.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarClientProxy.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/RestartableComponentBase.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/RestartableComponentSupport.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/RestartableSingletonFactory.java
- spring-pulsar/src/test/java/org/springframework/pulsar/core/CachingPulsarProducerFactoryTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/core/DefaultPulsarClientFactoryTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/core/PulsarClientProxyTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/core/RestartableSingletonFactoryTests.java
This commit introduces a restartable client that participates in SmartLifecycle and handles stop and start gracefully.
See #422
> Add graceful restart to client

- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/aot/ReactivePulsarRuntimeHints.java
- spring-pulsar/src/main/java/org/springframework/pulsar/aot/PulsarRuntimeHints.java
The shaded Caffeine lib used by the Reactive client had an incorrect prefix of 'org.springframework.pulsar'. This commit adjust the prefix to 'org.apache.pulsar.reactive'. Doing so surfaced more classes that needed to be registered for relective hints.
> Add AOT reflect hints for reactive caffeine cache

- spring-pulsar/src/test/java/org/springframework/pulsar/core/PulsarAdministrationIntegrationTests.java
Tests the case where a topic already exists w/ the exact number of partitions and the topic is requested to be created again. This scenario models a application restart when the user has a PulsarTopic bean defined.
> Add test to PulsarAdministrationIntegrationTests

- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/core/DefaultReactivePulsarSenderFactory.java
As it turns out the closeable() implementation of the reactive sender cache is properly clearing the cache therefore the reflective manual clear is not needed.
> Remove reflective cache clear on Reactive sender

- spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/pulsar.adoc
- spring-pulsar/src/main/java/org/springframework/pulsar/annotation/PulsarReader.java
- spring-pulsar/src/main/java/org/springframework/pulsar/annotation/PulsarReaderAnnotationBeanPostProcessor.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/AbstractPulsarReaderEndpoint.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/DefaultPulsarReaderContainerFactory.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/GenericReaderEndpointRegistry.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/PulsarReaderEndpoint.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/PulsarReaderEndpointRegistrar.java
- spring-pulsar/src/main/java/org/springframework/pulsar/reader/PulsarReaderContainerProperties.java
- spring-pulsar/src/test/java/org/springframework/pulsar/reader/PulsarReaderTests.java
This commit removes the subscription name from all PulsarReader areas. Readers do not have the concept of subscriptions and this was just a holdover from the PulsarListener codebase.
> Remove subscription name from PulsarReader

- spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/pulsar.adoc
- spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/reactive-pulsar.adoc
- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/config/annotation/ReactivePulsarListener.java
- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/config/annotation/ReactivePulsarListenerAnnotationBeanPostProcessor.java
- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/listener/ReactivePulsarContainerProperties.java
- spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/listener/ReactivePulsarListenerTests.java
- spring-pulsar/src/main/java/org/springframework/pulsar/annotation/PulsarListener.java
- spring-pulsar/src/main/java/org/springframework/pulsar/annotation/PulsarListenerAnnotationBeanPostProcessor.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/DefaultPulsarMessageListenerContainer.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/PulsarContainerProperties.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/PulsarListenerTests.java
This remove the default subscription type from `@PulsarListener` which then allows the defaults configured by `spring.pulsar.consumer.subscriptionType` to be respected. The Pulsar subscription type default is Exclusive (the previous default we had set in `@PulsarListener`) so if no value is set, ultimately `Exclusive` will still be used. 
See #488
> Remove subscription type default from PulsarListener

- spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/pulsar.adoc
- spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/reactive-pulsar.adoc
- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/config/MethodReactivePulsarListenerEndpoint.java
- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/config/annotation/ReactivePulsarListenerAnnotationBeanPostProcessor.java
- spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/listener/ReactivePulsarListenerCustomizerTests.java
- spring-pulsar/src/main/java/org/springframework/pulsar/annotation/PulsarListenerAnnotationBeanPostProcessor.java
- spring-pulsar/src/main/java/org/springframework/pulsar/annotation/PulsarReaderAnnotationBeanPostProcessor.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/MethodPulsarListenerEndpoint.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/MethodPulsarReaderEndpoint.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/PulsarListenerCustomizerTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/PulsarListenerTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/PulsarListenerTestsBase.java
- spring-pulsar/src/test/java/org/springframework/pulsar/reader/PulsarReaderCustomizerTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/reader/PulsarReaderTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/reader/PulsarReaderTestsBase.java
When there is only a single customizer and a single listener defined in the application then the customizer will automatically be associated with the listener. This works for @PulsarListener, @PulsarReader, and @ReactivePulsarListener.
See #480
> Automatically set customizer on listeners

- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/config/DefaultReactivePulsarListenerContainerFactory.java
- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/config/ReactivePulsarListenerEndpoint.java
- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/config/ReactivePulsarListenerEndpointAdapter.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/ConcurrentPulsarListenerContainerFactory.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/ListenerEndpoint.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/PulsarListenerEndpoint.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/PulsarListenerEndpointAdapter.java
This commit deprecates `PulsarListenerEndpointAdapter` and `ReactivePulsarListenerEndpointAdapter` in favor of default methods on `ListenerEndpoint` and its subinterfaces, which makes it a bit easier to provide custom `ListenerEndpoint` implementations.
> Deprecate (Reactive)PulsarListenerEndpointAdapter

- spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/authentication.adoc
This commit fixes the name of the `pluginClassName` for the OAuth2 provider in authentication.adoc
See #500
> Fix authentication doc for OAuth2

- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/config/annotation/ReactivePulsarListener.java
- spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/listener/ReactivePulsarListenerSpelTests.java
- spring-pulsar/src/main/java/org/springframework/pulsar/annotation/PulsarListener.java
- spring-pulsar/src/main/java/org/springframework/pulsar/annotation/PulsarReader.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/PulsarListenerSpelTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/reader/PulsarReaderSpelTests.java
> Add tests for SpEL attributes on @PulsarListener

- buildSrc/build.gradle
- gradle/build-libs.versions.toml
This commit adds `org.apache.commmons:commons-compress:1.25.0` to the buildSrc dependencies to ensure the same version required by the Spring Boot plugin (1.25.0) is used.
See https://github.com/spring-projects/spring-boot/issues/39148#issuecomment-1919569616
> Add commons-compress 1.25.0 to buildSrc libs

- spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/pulsar.adoc
- spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/reactive-pulsar.adoc
- spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/schema-info/schema-info-listener.adoc
- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/config/MethodReactivePulsarListenerEndpoint.java
- spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/listener/ReactivePulsarListenerAutoConsumeSchemaTests.java
- spring-pulsar-test/src/main/java/org/springframework/pulsar/test/support/model/UserPojo.java
- spring-pulsar-test/src/main/java/org/springframework/pulsar/test/support/model/UserRecord.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/MethodPulsarListenerEndpoint.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/MethodPulsarReaderEndpoint.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/DefaultSchemaResolver.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/Resolved.java
- spring-pulsar/src/test/java/org/springframework/pulsar/core/DefaultSchemaResolverTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/core/DefaultTopicResolverTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/core/ResolvedTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/PulsarListenerAutoConsumeSchemaTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/reader/PulsarReaderAutoConsumeSchemaTests.java
This PR adds support for AUTO_CONSUME schema type to:
- @PulsarListener
- @PulsarReader
- @ReactivePulsarListener
> [!NOTE]
> - [x] update docs
Resolves #380
> Add AUTO_CONSUME schema support

- spring-pulsar-docs/src/main/antora/modules/ROOT/pages/attributes/attributes-variables.adoc
- spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/schema-info/PulsarTemplate/template-snippet.adoc
- spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/schema-info/ReactivePulsarTemplate/template-snippet.adoc
- spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/schema-info/schema-info-template.adoc
- spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/core/ReactivePulsarTemplateTests.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/CachingPulsarProducerFactory.java
- spring-pulsar/src/test/java/org/springframework/pulsar/core/CachingPulsarProducerFactoryTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/core/PulsarTemplateTests.java
This commit adds support for producing raw JSON or Avro payloads with AUTO_SCHEMA.
> Add support for AUTO_PRODUCE schema

- gradle/libs.versions.toml
- spring-pulsar-dependencies/spring-pulsar-dependencies.gradle
- spring-pulsar-sample-apps/sample-failover-custom-router/build.gradle
- spring-pulsar-sample-apps/sample-failover-custom-router/src/main/resources/application.yml
- spring-pulsar-sample-apps/sample-pulsar-functions/sample-signup-app/build.gradle
- spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarTemplate.java
This commit removes Brave from being managed directly in the Java
Platform. Because the Brave version is already handled by Micrometer
Tracing BOM (which we import) there is no need to manage this
directly.
This commit adds back in the observation related dependencies into the
sample-failover-custom-router sample app. They were removed temporarily
as Spring Boot 3.3.0-SNAPSHOT had a bug when they bumped to Brave 6.0.1.
* Add in template and listener observation-enabled properties as
Spring Boot is currently setting these to false byu default.
* Remove observation related dependencies from the sample functions app
as they were not intended to be there in the first place.
> Remove Brave from Java Platform

- settings.gradle
- [com.gradle.enterprise](https://plugins.gradle.org/plugin/com.gradle.enterprise) from 3.12.6 to 3.16.2
- [io.spring.ge.conventions](https://github.com/spring-io/gradle-enterprise-conventions) from 0.0.13 to 0.0.15
Based on commits in spring-framework repo, internally spring team should support latest Gradle Enterprise plugin:
- Commit with note that only 3.15 version is supported: spring-projects/spring-framework@e3f185a696b0d6ca017a83366f24ed692573d14e 
- Commit with 3.16 version: spring-projects/spring-framework@b7e4fa16cae5f5a45fd661c51d558c8b9e5c39ae
> Upgrade enterprise gradle plugin

- spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/listener/ReactivePulsarListenerTombstoneTests.java
- spring-pulsar-reactive/src/test/resources/logback-test.xml
Due to flakiness of `ReactivePulsarListenerTombstoneTests$SingleComplexPayload` test, CI PR worflow has been failing intermetently. The exact reason of this flaky behaviour is not known so this PR adds an info log to give more insights on state of `receivedMessagesWithHeaders` before it is asserted.
- Reference issue: https://github.com/spring-projects/spring-pulsar/issues/561
- Updates `spring-pulsar-reactive/src/test/resources/logback-test.xml` by change log level of `ReactivePulsarListenerTombstoneTests$SingleComplexPayload` to `info`
- Adds an info log in `ReactivePulsarListenerTombstoneTests$SingleComplexPayload$shouldReceiveMessagesWithTombstone` test
> Add temporary info logs to analyse flaky test issue #561

- spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/pulsar.adoc
This commit adds docs to warn users to be careful when using Lambdas for ProducerBuilderCustomizers.
See #593
> Add docs for using Lambda producer customizers

- README.adoc
- spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/testing-applications.adoc
- spring-pulsar-docs/src/main/antora/modules/ROOT/pages/whats-new.adoc
- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/aot/package-info.java
- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/support/package-info.java
- spring-pulsar-test/spring-pulsar-test.gradle
- spring-pulsar-test/src/main/java/org/springframework/pulsar/test/support/PulsarTestContainerSupport.java
- spring-pulsar-test/src/main/java/org/springframework/pulsar/test/support/model/package-info.java
- spring-pulsar-test/src/main/java/org/springframework/pulsar/test/support/package-info.java
- spring-pulsar/src/main/java/org/springframework/pulsar/aot/package-info.java
This commit makes the spring-pulsar-test module available externally.
Additionally:
* Add missing package-info.java in several packages
* Update doc on how to use PulsarTestContainerSupport
> Publish the spring-pulsar-test module

- gradle/libs.versions.toml
- spring-pulsar-reactive/spring-pulsar-reactive.gradle
The pulsar-client-reactive-api transitively includes the pulsar-client-api. To insulate against different Pulsar client versions in the Pulsar Reactive Client and Spring Pulsar we exclude this transitive dependency and then include the version dictated by Spring Pulsar. This is the same technique that is already done for the pulsar-client-reactive-adapter.
> Add pulsar-client-reactive-api to spring-pulsar-reactive

- gradle/libs.versions.toml
- spring-pulsar-reactive/spring-pulsar-reactive.gradle
The pulsar-client-reactive-api transitively includes the pulsar-client-api. To insulate against different Pulsar client versions in the Pulsar Reactive Client and Spring Pulsar we exclude this transitive dependency and then include the version dictated by Spring Pulsar. This is the same technique that is already done for the pulsar-client-reactive-adapter.
> PORT "Add pulsar-client-reactive-api to spring-pulsar-reactive"

- gradle/libs.versions.toml
- spring-pulsar-test/spring-pulsar-test.gradle
The `spring-pulsar-test` module has a dependency on `org.testcontainers:testcontainers:1.19.7` which transitively brings in `org.apache.commons:commons-compress:1.24.0` with its 2 CVEs.
In order to rid the `spring-pulsar-test` module from these piggy-backed CVEs, this commit excludes `commons-compress` from the testcontainers dependencies and includes `commons-compress:1.26.1`.
> Override commons-compress version to 1.26.1

- spring-pulsar/src/main/java/org/springframework/pulsar/config/ConcurrentPulsarListenerContainerFactory.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/MethodPulsarListenerEndpoint.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarTemplate.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/TransactionProperties.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/DefaultPulsarMessageListenerContainer.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/PulsarContainerProperties.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/DefaultPulsarMessageListenerContainerTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/DefaultPulsarMessageListenerContainerTxnTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/PulsarListenerTxnTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/PulsarTxnTestsBase.java
- spring-pulsar/src/test/java/org/springframework/pulsar/transaction/PulsarTemplateLocalTransactionTests.java
This commit introduces a common transaction settings class used by `PulsarTemplate` and `PulsarContainerProperties`. This ensures common transaction properties and handling for both components.
See #27
cc: @jonas-grgt
> Introduce consistent transaction settings

- spring-pulsar/src/main/java/org/springframework/pulsar/annotation/BeanCustomizer.java
- spring-pulsar/src/main/java/org/springframework/pulsar/annotation/BeanCustomizerPostProcessor.java
- spring-pulsar/src/main/java/org/springframework/pulsar/annotation/PulsarBootstrapConfiguration.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/ConcurrentPulsarListenerContainerFactoryCustomizer.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarTemplateCustomizer.java
- spring-pulsar/src/test/java/org/springframework/pulsar/core/PulsarTemplateTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/ConcurrentPulsarListenerContainerFactoryCustomizerTests.java
This commit adds the notion of `BeanCustomizer` and a generic bean post processor that will apply any unique customizer to its target bean.
Included are concrete customizers for PulsarTemplate and ConcurrentPulsarListenerContainerFactory in order to make it easier to configure transactions to these components.
> Add support for bean customizers

- spring-pulsar/spring-pulsar.gradle
- spring-pulsar/src/test/java/org/springframework/pulsar/transaction/PulsarMixedTransactionTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/transaction/PulsarTxnTestsBase.java
- spring-pulsar/src/test/java/org/springframework/pulsar/transaction/PulsarTxnWithDbTxnTestsBase.java
- spring-pulsar/src/test/resources/transaction/init.sql
* Adds tests for using a transactional PulsarTemplate from within a `@Transactional` service method. The test sends a message to Pulsar and inserts a row in DB and does some form of rollback (or not) to make sure things are as expected.
See #661
> Add test for Pulsar synchronized transactions

- spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/reactive-pulsar/reactive-message-consumption.adoc
- spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/tombstones-reactive.adoc
Also clarify that `org.apache.pulsar.client.api.Messages<T>` are not supported in `@ReactivePulsarListener`.
Fixes #667
> Fix payload type in Reactive tombstone doc

- spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/reactive-pulsar/reactive-message-consumption.adoc
Updates the reactive-message-consumption.adoc to clarify the difference between the factory methods on `MessageResult` and `MessageUtils`.
Resolves #666
> Clarify use of MessageResult vs. MessageUtils

- spring-pulsar-docs/src/main/antora/modules/ROOT/nav.adoc
- spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/custom-object-mapper.adoc
- spring-pulsar-docs/src/main/antora/modules/ROOT/pages/whats-new.adoc
- spring-pulsar-reactive/spring-pulsar-reactive.gradle
- spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/core/ReactivePulsarTemplateTests.java
- spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/listener/DefaultReactivePulsarMessageListenerContainerTests.java
- spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/listener/ReactivePulsarListenerAutoConsumeSchemaTests.java
- spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/listener/ReactivePulsarListenerTests.java
- spring-pulsar-sample-apps/sample-imperative-produce-consume/build.gradle
- spring-pulsar-sample-apps/sample-imperative-produce-consume/src/main/java/com/example/ImperativeProduceAndConsumeApp.java
- spring-pulsar-sample-apps/sample-imperative-produce-consume/src/test/java/com/example/ImperativeProduceAndConsumeAppTests.java
- spring-pulsar-sample-apps/sample-reactive/build.gradle
- spring-pulsar-sample-apps/sample-reactive/src/main/java/com/example/ReactiveSpringPulsarBootApp.java
- spring-pulsar-sample-apps/sample-reactive/src/test/java/com/example/ReactiveSpringPulsarBootAppTests.java
- spring-pulsar/spring-pulsar.gradle
- spring-pulsar/src/main/java/org/springframework/pulsar/core/DefaultSchemaResolver.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/JSONSchemaUtil.java
- spring-pulsar/src/test/java/org/springframework/pulsar/core/CachingPulsarProducerFactoryTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/core/DefaultSchemaResolverTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/core/JsonSchemaUtilTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/core/PulsarTemplateTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/DefaultPulsarMessageListenerContainerTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/PulsarListenerAutoConsumeSchemaTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/PulsarListenerTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/reader/PulsarReaderAutoConsumeSchemaTests.java
- spring-pulsar/src/testFixtures/java/org/springframework/pulsar/test/model/UserPojo.java
- spring-pulsar/src/testFixtures/java/org/springframework/pulsar/test/model/UserRecord.java
- spring-pulsar/src/testFixtures/java/org/springframework/pulsar/test/model/json/UserRecordDeserializer.java
- spring-pulsar/src/testFixtures/java/org/springframework/pulsar/test/model/json/UserRecordObjectMapper.java
- spring-pulsar/src/testFixtures/java/org/springframework/pulsar/test/model/json/UserRecordSerializer.java
This commit adds support for a user-provided Jackson ObjectMapper to be used when de/serializing JSON messages.
Additionally, adds Gradle test fixtures to the spring-pulsar module and deprecates the UserRecord and UserPojo in spring-pulsar-test in favor of their equivalent in the test fixture.
See https://github.com/spring-projects/spring-pulsar/issues/723
> Add support for custom object mapper

- spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/pulsar-header.adoc
- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/config/MethodReactivePulsarListenerEndpoint.java
- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/config/annotation/ReactivePulsarListenerAnnotationBeanPostProcessor.java
- spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/listener/ReactivePulsarListenerTests.java
- spring-pulsar/src/main/java/org/springframework/pulsar/annotation/PulsarHeaderObjectMapperUtils.java
- spring-pulsar/src/main/java/org/springframework/pulsar/annotation/PulsarListenerAnnotationBeanPostProcessor.java
- spring-pulsar/src/main/java/org/springframework/pulsar/annotation/PulsarReaderAnnotationBeanPostProcessor.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/MethodPulsarListenerEndpoint.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/MethodPulsarReaderEndpoint.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/adapter/AbstractPulsarMessageToSpringMessageAdapter.java
- spring-pulsar/src/test/java/org/springframework/pulsar/annotation/PulsarHeaderObjectMapperUtilsTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/PulsarListenerTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/reader/PulsarReaderHeaderTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/support/header/JsonPulsarHeaderMapperTests.java
This commit adds support for a user-provided Jackson ObjectMapper to be used when deserializing JSON header values.
See #723
> Allow custom object mapper for headers

- integration-tests/src/intTest/java/org/springframework/pulsar/inttest/app/ImperativeAppConfig.java
- integration-tests/src/intTest/java/org/springframework/pulsar/inttest/app/ReactiveAppConfig.java
- integration-tests/src/intTest/java/org/springframework/pulsar/inttest/config/DefaultTenantAndNamespaceTests.java
- integration-tests/src/intTest/java/org/springframework/pulsar/inttest/config/ImperativeAppConfig.java
- integration-tests/src/intTest/java/org/springframework/pulsar/inttest/config/ReactiveAppConfig.java
- spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/pulsar-admin.adoc
- spring-pulsar-sample-apps/sample-failover-custom-router/build.gradle
- spring-pulsar-sample-apps/sample-failover-custom-router/src/main/java/com/example/FailoverConsumerApp.java
- spring-pulsar-sample-apps/sample-imperative-produce-consume/build.gradle
- spring-pulsar-sample-apps/sample-imperative-produce-consume/src/main/java/com/example/ImperativeProduceAndConsumeApp.java
Now that Spring Boot `3.4.0-M2` auto-configures the `PulsarTopicBuilder`, we want to update usage for ITs, samples, and docs accordingly.
> Use auto-configured PulsarTopicBuilder

- spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/pulsar/message-consumption.adoc
- spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/reactive-pulsar/reactive-message-consumption.adoc
This commit fixes invalid documentation references to `spring.pulsar.consumer.subscription.type` configuration property.
> Fix invalid configuration property references

- spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/pulsar/message-consumption.adoc
- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/config/DefaultReactivePulsarListenerContainerFactory.java
- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/config/annotation/ReactivePulsarListener.java
- spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/config/DefaultReactivePulsarListenerContainerFactoryTests.java
- spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/listener/ReactivePulsarListenerTests.java
- spring-pulsar/src/main/java/org/springframework/pulsar/annotation/PulsarListener.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/ConcurrentPulsarListenerContainerFactory.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/DefaultPulsarMessageListenerContainer.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/ConcurrentPulsarMessageListenerContainerTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/PulsarListenerTests.java
This commit moves the default subscription type from the `@PulsarListener` annotation to the container factory (props) which allows the `spring.pulsar.consumer.subscription-type` config prop to be respected.
See https://github.com/spring-projects/spring-boot/issues/42053
> Move default subscription type to factory

- spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/pulsar/message-consumption.adoc
- spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/reactive-pulsar/reactive-message-consumption.adoc
- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/config/DefaultReactivePulsarListenerContainerFactory.java
- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/config/annotation/ReactivePulsarListenerAnnotationBeanPostProcessor.java
- spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/listener/ReactivePulsarListenerTests.java
- spring-pulsar/src/main/java/org/springframework/pulsar/annotation/PulsarListenerAnnotationBeanPostProcessor.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/ConcurrentPulsarListenerContainerFactory.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/PulsarListenerEndpointRegistrar.java
- spring-pulsar/src/test/java/org/springframework/pulsar/config/ConcurrentPulsarListenerContainerFactoryTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/ConcurrentPulsarMessageListenerContainerTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/PulsarListenerTests.java
This commit moves the default subscription name from the `@PulsarListener` annotation to the container factory (props) which allows the `spring.pulsar.consumer.subscription.name` config prop to be respected.
See https://github.com/spring-projects/spring-boot/issues/42053
> Move default subscription name to factory

- spring-pulsar/src/main/java/org/springframework/pulsar/config/ConcurrentPulsarListenerContainerFactory.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/PulsarContainerProperties.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/ConcurrentPulsarMessageListenerContainerTests.java
This commit adds concurrency property to `PulsarContainerProperties` instead of managing it directly on
`ConcurrentPulsarListenerContainerFactory`, which provides consistency with both reactive counterpart and container properties in general.
Resolves: gh-820
> Add concurrency to PulsarContainerProperties

- spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/message-listener-startup-failure.adoc
- spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/pulsar/message-consumption.adoc
- spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/reactive-pulsar/reactive-message-consumption.adoc
- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/listener/DefaultReactivePulsarMessageListenerContainer.java
- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/listener/ReactivePulsarContainerProperties.java
- spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/listener/DefaultReactivePulsarMessageListenerContainerTests.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/StartupFailurePolicy.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/ConcurrentPulsarMessageListenerContainer.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/DefaultPulsarMessageListenerContainer.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/PulsarContainerProperties.java
- spring-pulsar/src/main/java/org/springframework/pulsar/reader/DefaultPulsarMessageReaderContainer.java
- spring-pulsar/src/main/java/org/springframework/pulsar/reader/PulsarReaderContainerProperties.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/ConcurrentPulsarMessageListenerContainerStartupFailureTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/DefaultPulsarMessageListenerContainerTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/DefaultPulsarMessageListenerContainerTxnTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/PulsarListenerTxnTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/reader/DefaultPulsarMessageReaderContainerTests.java
Previously, when a listener container failed to start, it would only log the exception. This commit introduces `StartupFailurePolicy` that allows listener containers to CONTINUE, STOP, RETRY when an error is encountered on startup.
See #445
See #816
> Add startup failure policy to listener

- integration-tests/src/intTest/java/org/springframework/pulsar/inttest/listener/PulsarListenerIntegrationTests.java
- integration-tests/src/intTest/java/org/springframework/pulsar/inttest/listener/ReactivePulsarListenerIntegrationTests.java
This commit adds ITs to exercise the ability to configure the `@PulsarListener` / `@ReactivePulsarListener` subscription name and type using Spring Boot config props.
> [!CAUTION]
> Requires https://github.com/spring-projects/spring-boot/pull/42067 to run successfully
> Add IT for config props driven listeners

- spring-pulsar-docs/src/main/antora/modules/ROOT/pages/whats-new.adoc
- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/config/DefaultReactivePulsarListenerContainerFactory.java
- spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/config/DefaultReactivePulsarListenerContainerFactoryTests.java
- spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/listener/ReactivePulsarListenerSpelTests.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/AbstractPulsarListenerContainerFactory.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/AbstractPulsarReaderContainerFactory.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/DefaultPulsarReaderContainerFactory.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/GenericListenerEndpointRegistry.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/GenericReaderEndpointRegistry.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/ListenerEndpoint.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/PulsarContainerFactory.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/PulsarReaderEndpoint.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/ReaderContainerFactory.java
- spring-pulsar/src/test/java/org/springframework/pulsar/config/ConcurrentPulsarListenerContainerFactoryTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/config/DefaultPulsarReaderContainerFactoryTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/ConcurrentPulsarMessageListenerContainerTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/PulsarListenerSpelTests.java
This introduces a common interface for all message listener containers. Prior to this commit, the reader and listener containers had no common abstraction. This is needed to introduce a generic container factory customizer in Spring Boot.
> Add common container factory interface

- spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/pulsar/transactions.adoc
- spring-pulsar-docs/src/main/antora/modules/ROOT/pages/whats-new.adoc
- spring-pulsar/src/main/java/org/springframework/pulsar/annotation/ConcurrentPulsarListenerContainerFactoryBeanCustomizerPostProcessor.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/ConcurrentPulsarListenerContainerFactoryCustomizer.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/ConcurrentPulsarListenerContainerFactoryCustomizerTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/PulsarListenerTxnTests.java
The purpose of `ConcurrentPulsarListenerContainerFactoryCustomizer` was to customize the Spring Boot auto-configured message container factories. However, Spring Boot has introduced a generic message container factory customizer `PulsarContainerFactoryCustomizer` that removes the need for this customizer.
This commit deprecates the Spring for Apache Pulsar customizer in favor of the Spring Boot provided generic container factory customizer.
> Deprecate container factory customizer

- spring-pulsar-docs/src/main/antora/modules/ROOT/pages/whats-new.adoc
- spring-pulsar/src/main/java/org/springframework/pulsar/core/DefaultPulsarReaderFactory.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarReaderFactory.java
- spring-pulsar/src/main/java/org/springframework/pulsar/reader/DefaultPulsarMessageReaderContainer.java
- spring-pulsar/src/test/java/org/springframework/pulsar/core/DefaultPulsarReaderFactoryTests.java
This commit replaces the checked `PulsarClientException` with the unchecked `PulsarException` on the `PulsarReaderFactory#createReader` API.
> Use unchecked exception on reader factory

- integration-tests/src/intTest/java/org/springframework/pulsar/inttest/listener/PulsarListenerIntegrationTests.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/DefaultPulsarConsumerFactory.java
Prior to this commit, only the topics specified on the `@PulsarListener` were being fully qualified in the `DefaultPulsarConsumerFactory`. 
With this change all topics (including the default topics driven by the Spring Boot `spring.pulsar.consumer.topics` config prop) are fully-qualified.
.
> Ensure default topics are fully qualified

- integration-tests/integration-tests.gradle
- integration-tests/src/intTest/java/org/springframework/pulsar/inttest/logging/PulsarTemplateLambdaWarnLoggerTests.java
- integration-tests/src/intTest/resources/logback-test.xml
- spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarTemplate.java
- spring-pulsar/src/main/java/org/springframework/pulsar/support/JavaUtils.java
- spring-pulsar/src/main/java/org/springframework/pulsar/support/internal/logging/EveryNthSampler.java
- spring-pulsar/src/main/java/org/springframework/pulsar/support/internal/logging/LambdaCustomizerWarnLogger.java
- spring-pulsar/src/test/java/org/springframework/pulsar/support/JavaUtilsTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/support/internal/logging/EveryNthSamplerTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/support/internal/logging/LambdaCustomizerWarnLoggerTests.java
- src/checkstyle/checkstyle-suppressions.xml
This adjusts the `PulsarTemplate` to log a warning when a user provides a `ProducerBuilderCustomizer` that is implemented as a Java Lambda. This is important as the customizer is used as part of the producer cache key and if not implemented properly will effectively disable producer caching and write performance will degrade.
See #809
> Log a warning when Lambda customizer used

- spring-pulsar/src/main/java/org/springframework/pulsar/function/PulsarFunctionAdministration.java
- spring-pulsar/src/main/java/org/springframework/pulsar/support/header/PulsarHeaderMatcher.java
- src/checkstyle/checkstyle-suppressions.xml
- src/checkstyle/checkstyle.xml
This commit makes sure that all usages of String toLowerCase and toUpperCase specify a Locale (default of Locale.ROOT).
Also, a checkstyle rule is added to prevent usage of the no-arg variant of String toLowerCase and toUpperCase.
> Specify locale in toLowerCase|toUpperCase

- spring-pulsar/spring-pulsar.gradle
This commit excludes the `protobuf-java` unshaded transitive dependency from the `pulsar-client-all` library. This allows the version of the optional `protobuf-java` dependency to be controlled by `spring-pulsar`.
Resolves #876
> Exclude protobuf-java from pulsar-client-all

- spring-pulsar-docs/src/main/antora/modules/ROOT/pages/appendix/version-compatibility.adoc
This commit removes version 0.2.x from the compatibility matrix in an effort to curb the current use of version 0.2.x.
> Remove version 0.2.x from docs

- .github/workflows/check-samples.yml
- spring-pulsar-sample-apps/sample-failover-custom-router/build.gradle
- spring-pulsar-sample-apps/sample-imperative-produce-consume/build.gradle
- spring-pulsar-sample-apps/sample-pulsar-binder/build.gradle
- spring-pulsar-sample-apps/sample-pulsar-functions/sample-signup-app/build.gradle
- spring-pulsar-sample-apps/sample-pulsar-functions/sample-signup-function/build.gradle
- spring-pulsar-sample-apps/sample-pulsar-reader/build.gradle
- spring-pulsar-sample-apps/sample-reactive/build.gradle
Adds the ability to specify the Pulsar client version when running the samples apps.
Uses this new capability to add entries to the `check-samples.yml` compatibility test matrix to include Pulsar 4.0.x.
See #923
> Add Pulsar 4.0.x compatibility tests

- spring-pulsar-docs/src/main/antora/modules/ROOT/pages/appendix/version-compatibility.adoc
This commit adds 4.0.x Pulsar client to the compatibility matrix doc.
Resolves #933
> Add Pulsar 4.0.x to compatibility matrix doc

- .github/dco.yml
- CODE_OF_CONDUCT.adoc
- CONTRIBUTING.adoc
> Update from CLA to DCO (1.1.x)

- spring-pulsar/src/main/java/org/springframework/pulsar/listener/DefaultPulsarMessageListenerContainer.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/DefaultPulsarConsumerErrorHandlerTests.java
> Backport "Fix batch listener error handling" (1.1.x)

- spring-pulsar/src/main/java/org/springframework/pulsar/listener/DefaultPulsarMessageListenerContainer.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/DefaultPulsarConsumerErrorHandlerTests.java
Updates the batch listener error handler code to handle the case where there is only a single outstanding
message in the batch list when retries are expired.
See #998
> Backport "Fix batch listener error handling" (1.0.x)

- spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/pulsar/message-consumption.adoc
- spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/reactive-pulsar/reactive-message-consumption.adoc
The docs has code examples using a consumer property named `ackTimeout`. However, the actual property name is `ackTimeoutMillis`. This updates those references.
Resolves #1010
> Fix references to invalid 'ackTimeout' property

- spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/pulsar/message-consumption.adoc
- spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/reactive-pulsar/reactive-message-consumption.adoc
The docs has code examples using a consumer property named `ackTimeout`. However, the actual property name is `ackTimeoutMillis`. This updates those references.
Resolves #1010
(cherry picked from commit 03c0da3bce53bae311c65ee066f59f697c039dde)
> Fix references to invalid 'ackTimeout' property (#1015)

- spring-pulsar-docs/src/main/antora/modules/ROOT/pages/reference/pulsar-header.adoc
- spring-pulsar/src/main/java/org/springframework/pulsar/support/header/AbstractPulsarHeaderMapper.java
- spring-pulsar/src/test/java/org/springframework/pulsar/support/header/AbstractPulsarHeaderMapperTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/support/header/ToStringPulsarHeaderMapperTests.java
This allows pulsar metadata headers, which are excluded on the outbound messages by default, to be included in the outbound message headers.
Resolves #1037
> Allow pulsar metadata headers to be mapped outbound

- spring-pulsar/src/main/java/org/springframework/pulsar/listener/DefaultPulsarMessageListenerContainer.java
This creates a separate logger for DefaultPulsarMessageListenerContainer that it uses to log exceptions thrown from listener callback methods.
The exceptions are still logged at debug level in order to not change behavior in a patch release. However, the log category used by the logger can then be set to debug level but not spam the logs with the other debug statements in the listener container.
Resolves #1008
> Use separate logger for PulsarListener exceptions

- spring-pulsar/src/test/java/org/springframework/pulsar/function/PulsarFunctionAdministrationTests.java
This fixes some AssertJ deprecations that came along w/ the update to AssertJ `3.73`.
> Fix deprecation AssertJ calls

- spring-pulsar/src/main/java/org/springframework/pulsar/core/DefaultSchemaResolver.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/DefaultTopicResolver.java
- spring-pulsar/src/test/java/org/springframework/pulsar/core/DefaultSchemaResolverTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/core/DefaultTopicResolverTests.java
This commit updates the DefaultTopicResolver and DefaulSchemaResolver to use String class names rather than Class instances as map keys for their custom mappings.
Resolves #1078
> Stop using Class as map key for custom mappings

- spring-pulsar/src/main/java/org/springframework/pulsar/core/DefaultSchemaResolver.java
- spring-pulsar/src/main/java/org/springframework/pulsar/core/DefaultTopicResolver.java
- spring-pulsar/src/test/java/org/springframework/pulsar/core/DefaultSchemaResolverTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/core/DefaultTopicResolverTests.java
This fixes the DefaultTopicResolver.getCustomTopicMappings and DefaultSchemaResolver.getCustomSchemaMappings APIs to actually return the mappings and also use ClassUtils.forName instead of Class.forName to safely load the class from string key.
> Fix getCustomMappings API for resolvers

- buildSrc/src/main/java/org/springframework/pulsar/gradle/JavaConventionsPlugin.java
- integration-tests/src/intTest/java/org/springframework/pulsar/inttest/config/DefaultTenantAndNamespaceTests.java
- integration-tests/src/intTest/java/org/springframework/pulsar/inttest/logging/PulsarTemplateLambdaWarnLoggerTests.java
- spring-pulsar-sample-apps/sample-pulsar-functions/sample-signup-app/src/main/java/org/springframework/pulsar/sample/signup/config/AppConfig.java
- spring-pulsar/src/main/java/org/springframework/pulsar/config/ConcurrentPulsarListenerContainerFactory.java
- spring-pulsar/src/test/java/org/springframework/pulsar/core/SchemaResolverTests.java
- src/checkstyle/checkstyle.xml
This commit updates to Javaformat to 0.0.47 and the Checkstyle tools to 10.25.0.
The `SpringAnnotationLocationCheck` has also been added to the checkstyle rules in order to prepare for the migration to Jspecify for nullability constraints.
Also, various code has been updated to abide by the new format and checkstyle rules in the updated versions.
See #1150
> Update to Spring Javaformat / checkstyle (prepare for JSpecify)

- spring-pulsar-cache-provider-caffeine/spring-pulsar-cache-provider-caffeine.gradle
This commit adjusts the shading in the spring-pulsar-cache-provider-caffeine module to not include the `org.checkerframework:checker-qual` in the shaded jar.
> Stop shading checker-qual in caffeine cache provider (2.0.x line)

- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/config/annotation/ReactivePulsarListenerAnnotationBeanPostProcessor.java
- spring-pulsar/src/main/java/org/springframework/pulsar/annotation/PulsarListenerAnnotationBeanPostProcessor.java
This commit fixes the case where SpEL expressions using the `__listener.` bean ref were failing due to the concrete impls of the `AbstractPulsarAnnotationsBeanPostProcessor` hiding/overriding their parent's `listenerScope` field by removing the `listenerScope` field from the following concrete impls:
- PulsarListenerAnnotationBeanPostProcessor
- ReactivePulsarListenerAnnotationBeanPostProcessor
Fixes #1169
> Remove listenerScope field override in annotation processors

- spring-pulsar/spring-pulsar.gradle
The improvements introduced in [this PR](https://github.com/apache/pulsar/pull/23647) include handling `javax.activation` via shading and migrating from javax to jakarta. Given these changes, we should remove some of the now unnecessary exclusions.
Fix #963
> Remove no longer needed exclusions from pulsar-client-all

- spring-pulsar/spring-pulsar.gradle
> Cleanup exclusions

- gradle/libs.versions.toml
- spring-pulsar-dependencies/spring-pulsar-dependencies.gradle
- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/listener/DefaultReactivePulsarMessageListenerContainer.java
- spring-pulsar-reactive/src/main/java/org/springframework/pulsar/reactive/listener/ReactivePulsarContainerProperties.java
- spring-pulsar-reactive/src/test/java/org/springframework/pulsar/reactive/listener/DefaultReactivePulsarMessageListenerContainerTests.java
- spring-pulsar/spring-pulsar.gradle
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/DefaultPulsarMessageListenerContainer.java
- spring-pulsar/src/main/java/org/springframework/pulsar/listener/PulsarContainerProperties.java
- spring-pulsar/src/main/java/org/springframework/pulsar/reader/DefaultPulsarMessageReaderContainer.java
- spring-pulsar/src/main/java/org/springframework/pulsar/reader/PulsarReaderContainerProperties.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/ConcurrentPulsarMessageListenerContainerStartupFailureTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/listener/DefaultPulsarMessageListenerContainerTests.java
- spring-pulsar/src/test/java/org/springframework/pulsar/reader/DefaultPulsarMessageReaderContainerTests.java
This PR replaces Spring Retry w/ Core Retry in Spring Pulsar.
> [!NOTE]
> **Remaining items:**
> - [ ] update `whats-news.adoc`
Resolves #1224
cc: @snicoll @jhoeller
> Replace spring-retry with core-retry
